import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import SideDrawer from "@/components/ui/SideDrawer";
import {
  fetchTestCases,
  createTestCase,
  deleteTestCase,
  generateTestCases,
  fetchTestCycles,
  createTestCycle,
  updateTestCycle,
  deleteTestCycle,
  fetchTestExecutions,
  addTestToCycle,
  updateTestExecution,
  fetchTestCoverage,
} from "@/services/api";
import type { TestCase, TestCycle, TestExecution, TestCoverage } from "@/types";
import styles from "./TestsTab.module.css";

import {
  RiAddLine,
  RiSparklingLine,
  RiDeleteBinLine,
  RiCheckLine,
  RiCloseLine,
  RiAlertLine,
  RiSkipForwardLine,
  RiFlashlightLine,
  RiTestTubeLine,
  RiLoopLeftLine,
  RiShieldCheckLine,
  RiTimeLine,
  RiArrowLeftLine,
} from "react-icons/ri";

function EOSBadge() {
  return (
    <span className={styles.eosBadge}>
      <RiSparklingLine size={9} />
      EOS
    </span>
  );
}

const PRIORITY_COLOR: Record<string, string> = {
  high: "var(--red)",
  medium: "var(--amber)",
  low: "var(--green)",
};

const EXEC_STATUS_CONFIG: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  pending:  { label: "Pending",  color: "var(--text-3)",  icon: <RiTimeLine size={12} /> },
  passed:   { label: "Passed",   color: "var(--green)",   icon: <RiCheckLine size={12} /> },
  failed:   { label: "Failed",   color: "var(--red)",     icon: <RiCloseLine size={12} /> },
  blocked:  { label: "Blocked",  color: "var(--amber)",   icon: <RiAlertLine size={12} /> },
  skipped:  { label: "Skipped",  color: "var(--text-2)",  icon: <RiSkipForwardLine size={12} /> },
};

type SubTab = "cases" | "cycles" | "coverage";

// ── Test Cases View ────────────────────────────────────────────────────────────

function TestCasesView({ pod }: { pod: string }) {
  const qc = useQueryClient();
  const { data: cases = [], isLoading } = useQuery({
    queryKey: ["test-cases", pod],
    queryFn: () => fetchTestCases(pod),
  });

  const [drawerCase, setDrawerCase] = useState<TestCase | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [showGenerate, setShowGenerate] = useState(false);

  const [formTitle, setFormTitle] = useState("");
  const [formDesc, setFormDesc] = useState("");
  const [formPre, setFormPre] = useState("");
  const [formPriority, setFormPriority] = useState("medium");
  const [formTicketKey, setFormTicketKey] = useState("");
  const [formSteps, setFormSteps] = useState([{ step: "", expected_result: "" }]);

  const [genTicketKey, setGenTicketKey] = useState("");
  const [genSummary, setGenSummary] = useState("");
  const [genDesc, setGenDesc] = useState("");
  const [genCount, setGenCount] = useState(5);

  const createMut = useMutation({
    mutationFn: () =>
      createTestCase(pod, {
        title: formTitle,
        description: formDesc || undefined,
        preconditions: formPre || undefined,
        steps: formSteps.filter((s) => s.step.trim()),
        priority: formPriority,
        ticket_key: formTicketKey || undefined,
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["test-cases", pod] });
      toast.success("Test case created");
      resetForm();
      setShowCreate(false);
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const deleteMut = useMutation({
    mutationFn: (caseId: string) => deleteTestCase(pod, caseId),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["test-cases", pod] });
      toast.success("Test case deleted");
      setDrawerCase(null);
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const generateMut = useMutation({
    mutationFn: () =>
      generateTestCases(pod, {
        ticket_key: genTicketKey,
        ticket_summary: genSummary,
        ticket_description: genDesc || undefined,
        count: genCount,
      }),
    onSuccess: (newCases) => {
      qc.invalidateQueries({ queryKey: ["test-cases", pod] });
      toast.success(`${newCases.length} test cases generated by EOS`);
      setShowGenerate(false);
      setGenTicketKey("");
      setGenSummary("");
      setGenDesc("");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  function resetForm() {
    setFormTitle("");
    setFormDesc("");
    setFormPre("");
    setFormPriority("medium");
    setFormTicketKey("");
    setFormSteps([{ step: "", expected_result: "" }]);
  }

  function addStep() {
    setFormSteps([...formSteps, { step: "", expected_result: "" }]);
  }

  function updateStep(idx: number, field: "step" | "expected_result", val: string) {
    const updated = [...formSteps];
    updated[idx][field] = val;
    setFormSteps(updated);
  }

  function removeStep(idx: number) {
    setFormSteps(formSteps.filter((_, i) => i !== idx));
  }

  if (isLoading) return <div className={styles.loading}>Loading test cases…</div>;

  return (
    <div>
      <div className={styles.subHeader}>
        <span className={styles.count}>{cases.length} test case{cases.length !== 1 ? "s" : ""}</span>
        <div className={styles.actions}>
          <button className={styles.generateBtn} onClick={() => setShowGenerate(true)}>
            <RiSparklingLine size={13} /> Generate with EOS
          </button>
          <button className={styles.createBtn} onClick={() => { resetForm(); setShowCreate(true); }}>
            <RiAddLine size={14} /> New Test Case
          </button>
        </div>
      </div>

      {/* AI Generate Form */}
      {showGenerate && (
        <div className={styles.form}>
          <div className={styles.formTitle}>
            <EOSBadge /> Generate test cases from ticket
          </div>
          <div className={styles.formRow}>
            <input
              className={styles.input}
              placeholder="Ticket key (e.g. DPAI-123)"
              value={genTicketKey}
              onChange={(e) => setGenTicketKey(e.target.value)}
            />
            <input
              className={styles.input}
              placeholder="Count"
              type="number"
              min={1}
              max={10}
              value={genCount}
              onChange={(e) => setGenCount(Number(e.target.value))}
              style={{ maxWidth: 80 }}
            />
          </div>
          <input
            className={styles.input}
            placeholder="Ticket summary / title"
            value={genSummary}
            onChange={(e) => setGenSummary(e.target.value)}
          />
          <textarea
            className={styles.textarea}
            placeholder="Ticket description (optional — helps EOS generate better cases)"
            value={genDesc}
            onChange={(e) => setGenDesc(e.target.value)}
            rows={3}
          />
          <div className={styles.formActions}>
            <button
              className={styles.generateBtn}
              onClick={() => generateMut.mutate()}
              disabled={!genTicketKey.trim() || !genSummary.trim() || generateMut.isPending}
            >
              {generateMut.isPending ? "Generating…" : <><RiSparklingLine size={12} /> Generate</>}
            </button>
            <button className={styles.cancelBtn} onClick={() => setShowGenerate(false)}>Cancel</button>
          </div>
        </div>
      )}

      {/* Manual Create Form */}
      {showCreate && (
        <div className={styles.form}>
          <div className={styles.formTitle}>New Test Case</div>
          <input
            className={styles.input}
            placeholder="Title"
            value={formTitle}
            onChange={(e) => setFormTitle(e.target.value)}
            required
          />
          <div className={styles.formRow}>
            <input
              className={styles.input}
              placeholder="Linked ticket key (optional)"
              value={formTicketKey}
              onChange={(e) => setFormTicketKey(e.target.value)}
            />
            <select
              className={styles.select}
              value={formPriority}
              onChange={(e) => setFormPriority(e.target.value)}
            >
              <option value="high">High</option>
              <option value="medium">Medium</option>
              <option value="low">Low</option>
            </select>
          </div>
          <textarea
            className={styles.textarea}
            placeholder="Description"
            value={formDesc}
            onChange={(e) => setFormDesc(e.target.value)}
            rows={2}
          />
          <textarea
            className={styles.textarea}
            placeholder="Preconditions"
            value={formPre}
            onChange={(e) => setFormPre(e.target.value)}
            rows={2}
          />
          <div className={styles.stepsSection}>
            <div className={styles.stepsHeader}>
              <span className={styles.stepsLabel}>Steps</span>
              <button type="button" className={styles.addStepBtn} onClick={addStep}>
                <RiAddLine size={12} /> Add Step
              </button>
            </div>
            {formSteps.map((s, i) => (
              <div key={i} className={styles.stepRow}>
                <span className={styles.stepNum}>{i + 1}</span>
                <input
                  className={styles.input}
                  placeholder="Action"
                  value={s.step}
                  onChange={(e) => updateStep(i, "step", e.target.value)}
                />
                <input
                  className={styles.input}
                  placeholder="Expected result"
                  value={s.expected_result}
                  onChange={(e) => updateStep(i, "expected_result", e.target.value)}
                />
                <button className={styles.removeStepBtn} onClick={() => removeStep(i)}>
                  <RiCloseLine size={12} />
                </button>
              </div>
            ))}
          </div>
          <div className={styles.formActions}>
            <button
              className={styles.saveBtn}
              onClick={() => createMut.mutate()}
              disabled={!formTitle.trim() || createMut.isPending}
            >
              Create
            </button>
            <button className={styles.cancelBtn} onClick={() => { resetForm(); setShowCreate(false); }}>Cancel</button>
          </div>
        </div>
      )}

      {/* Cases List */}
      <div className={styles.caseList}>
        {cases.map((tc) => (
          <div key={tc.id} className={styles.caseRow} onClick={() => setDrawerCase(tc)}>
            <div className={styles.caseLeft}>
              <span
                className={styles.priorityDot}
                style={{ background: PRIORITY_COLOR[tc.priority] }}
                title={tc.priority}
              />
              <span className={styles.caseTitle}>{tc.title}</span>
              {tc.ai_generated && <EOSBadge />}
            </div>
            <div className={styles.caseMeta}>
              {tc.ticket_key && (
                <span className={styles.ticketKey}>{tc.ticket_key}</span>
              )}
              <span className={styles.stepsCount}>{tc.steps?.length ?? 0} steps</span>
            </div>
          </div>
        ))}
        {cases.length === 0 && !showCreate && !showGenerate && (
          <div className={styles.empty}>
            No test cases yet. Create one manually or generate with EOS.
          </div>
        )}
      </div>

      {/* Case Detail Drawer */}
      {drawerCase && (
        <SideDrawer
          open={Boolean(drawerCase)}
          onClose={() => setDrawerCase(null)}
          size="md"
          title={drawerCase.title}
          badge={
            drawerCase.ai_generated ? (
              <span className={styles.aiGenBadge}><EOSBadge /></span>
            ) : undefined
          }
        >
          <div className={styles.drawerBody}>
            <div className={styles.drawerMeta}>
              <span style={{ color: PRIORITY_COLOR[drawerCase.priority] }}>
                ● {drawerCase.priority} priority
              </span>
              {drawerCase.ticket_key && (
                <span className={styles.ticketKey}>{drawerCase.ticket_key}</span>
              )}
            </div>

            {drawerCase.description && (
              <div className={styles.drawerSection}>
                <div className={styles.drawerSectionTitle}>Description</div>
                <p className={styles.drawerText}>{drawerCase.description}</p>
              </div>
            )}

            {drawerCase.preconditions && (
              <div className={styles.drawerSection}>
                <div className={styles.drawerSectionTitle}>Preconditions</div>
                <p className={styles.drawerText}>{drawerCase.preconditions}</p>
              </div>
            )}

            {drawerCase.steps && drawerCase.steps.length > 0 && (
              <div className={styles.drawerSection}>
                <div className={styles.drawerSectionTitle}>Steps</div>
                <div className={styles.drawerSteps}>
                  {drawerCase.steps.map((s, i) => (
                    <div key={i} className={styles.drawerStep}>
                      <span className={styles.drawerStepNum}>{i + 1}</span>
                      <div className={styles.drawerStepContent}>
                        <div className={styles.drawerStepAction}>{s.step}</div>
                        <div className={styles.drawerStepExpected}>→ {s.expected_result}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className={styles.drawerActions}>
              <button
                className={styles.drawerDangerBtn}
                onClick={() => deleteMut.mutate(drawerCase.id)}
                disabled={deleteMut.isPending}
              >
                <RiDeleteBinLine size={13} /> Delete
              </button>
            </div>
          </div>
        </SideDrawer>
      )}
    </div>
  );
}

// ── Cycles View ────────────────────────────────────────────────────────────────

function CyclesView({ pod }: { pod: string }) {
  const qc = useQueryClient();
  const { data: cycles = [], isLoading } = useQuery({
    queryKey: ["test-cycles", pod],
    queryFn: () => fetchTestCycles(pod),
  });
  const { data: allCases = [] } = useQuery({
    queryKey: ["test-cases", pod],
    queryFn: () => fetchTestCases(pod),
  });

  const [activeCycle, setActiveCycle] = useState<TestCycle | null>(null);
  const [executions, setExecutions] = useState<TestExecution[]>([]);
  const [loadingExecs, setLoadingExecs] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [showAddCase, setShowAddCase] = useState(false);
  const [formName, setFormName] = useState("");
  const [formDesc, setFormDesc] = useState("");

  const createMut = useMutation({
    mutationFn: () => createTestCycle(pod, { name: formName, description: formDesc || undefined }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["test-cycles", pod] });
      toast.success("Test cycle created");
      setShowCreate(false);
      setFormName("");
      setFormDesc("");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const deleteMut = useMutation({
    mutationFn: (cycleId: string) => deleteTestCycle(pod, cycleId),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["test-cycles", pod] });
      toast.success("Cycle deleted");
      setActiveCycle(null);
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const statusMut = useMutation({
    mutationFn: ({ cycleId, status }: { cycleId: string; status: string }) =>
      updateTestCycle(pod, cycleId, { status }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["test-cycles", pod] }),
    onError: (e: Error) => toast.error(e.message),
  });

  const execMut = useMutation({
    mutationFn: ({ execId, status, notes }: { execId: string; status: string; notes?: string }) =>
      updateTestExecution(pod, execId, { status, notes }),
    onSuccess: async () => {
      if (activeCycle) {
        const updated = await fetchTestExecutions(pod, activeCycle.id);
        setExecutions(updated);
      }
      qc.invalidateQueries({ queryKey: ["test-cycles", pod] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const addCaseMut = useMutation({
    mutationFn: (testCaseId: string) => addTestToCycle(pod, activeCycle!.id, testCaseId),
    onSuccess: async () => {
      if (activeCycle) {
        const updated = await fetchTestExecutions(pod, activeCycle.id);
        setExecutions(updated);
        qc.invalidateQueries({ queryKey: ["test-cycles", pod] });
        toast.success("Test case added to cycle");
      }
      setShowAddCase(false);
    },
    onError: (e: Error) => toast.error(e.message),
  });

  async function openCycle(cycle: TestCycle) {
    setActiveCycle(cycle);
    setLoadingExecs(true);
    try {
      const execs = await fetchTestExecutions(pod, cycle.id);
      setExecutions(execs);
    } finally {
      setLoadingExecs(false);
    }
  }

  const addedCaseIds = new Set(executions.map((e) => e.test_case_id));
  const availableCases = allCases.filter((c) => !addedCaseIds.has(c.id));

  if (activeCycle) {
    const cfg = (s: string) => EXEC_STATUS_CONFIG[s] ?? EXEC_STATUS_CONFIG.pending;
    const passedPct = activeCycle.total > 0
      ? Math.round((executions.filter((e) => e.status === "passed").length / activeCycle.total) * 100)
      : 0;

    return (
      <div>
        <div className={styles.subHeader}>
          <button className={styles.backBtn} onClick={() => setActiveCycle(null)}>
            <RiArrowLeftLine size={14} /> All Cycles
          </button>
          <button className={styles.createBtn} onClick={() => setShowAddCase(true)}>
            <RiAddLine size={14} /> Add Test Case
          </button>
        </div>

        <div className={styles.cycleDetailHeader}>
          <h3 className={styles.cycleDetailName}>{activeCycle.name}</h3>
          <div className={styles.cycleDetailMeta}>
            <div className={styles.cycleProgress}>
              <div className={styles.cycleProgressBar}>
                <div className={styles.cycleProgressFill} style={{ width: `${passedPct}%` }} />
              </div>
              <span className={styles.cycleProgressLabel}>{passedPct}% passed</span>
            </div>
            <div className={styles.cyclePills}>
              <span className={styles.pillPassed}>{executions.filter((e) => e.status === "passed").length} passed</span>
              <span className={styles.pillFailed}>{executions.filter((e) => e.status === "failed").length} failed</span>
              <span className={styles.pillBlocked}>{executions.filter((e) => e.status === "blocked").length} blocked</span>
              <span className={styles.pillPending}>{executions.filter((e) => e.status === "pending").length} pending</span>
            </div>
          </div>
          <div className={styles.cycleDetailActions}>
            {activeCycle.status === "planning" && (
              <button className={styles.startBtn} onClick={() => statusMut.mutate({ cycleId: activeCycle.id, status: "active" })}>
                <RiFlashlightLine size={12} /> Start Cycle
              </button>
            )}
            {activeCycle.status === "active" && (
              <button className={styles.completeBtn} onClick={() => statusMut.mutate({ cycleId: activeCycle.id, status: "completed" })}>
                <RiCheckLine size={12} /> Complete
              </button>
            )}
            <button className={styles.deleteSmallBtn} onClick={() => deleteMut.mutate(activeCycle.id)}>
              <RiDeleteBinLine size={12} />
            </button>
          </div>
        </div>

        {showAddCase && (
          <div className={styles.addCasePanel}>
            <div className={styles.addCasePanelTitle}>Add test cases to this cycle</div>
            {availableCases.length === 0 ? (
              <div className={styles.empty}>All test cases are already in this cycle.</div>
            ) : (
              availableCases.map((tc) => (
                <div key={tc.id} className={styles.addCaseRow}>
                  <span className={styles.addCaseTitle}>{tc.title}</span>
                  {tc.ticket_key && <span className={styles.ticketKey}>{tc.ticket_key}</span>}
                  <button className={styles.addCaseAddBtn} onClick={() => addCaseMut.mutate(tc.id)}>
                    <RiAddLine size={12} />
                  </button>
                </div>
              ))
            )}
            <button className={styles.cancelBtn} style={{ marginTop: 8 }} onClick={() => setShowAddCase(false)}>Done</button>
          </div>
        )}

        {loadingExecs ? (
          <div className={styles.loading}>Loading executions…</div>
        ) : executions.length === 0 ? (
          <div className={styles.empty}>No test cases in this cycle yet. Add some above.</div>
        ) : (
          <div className={styles.execList}>
            {executions.map((ex) => {
              const c = cfg(ex.status);
              return (
                <div key={ex.id} className={styles.execRow}>
                  <div className={styles.execLeft}>
                    <span style={{ color: c.color }}>{c.icon}</span>
                    <span className={styles.execTitle}>{ex.test_case?.title ?? "—"}</span>
                    {ex.test_case?.ai_generated && <EOSBadge />}
                  </div>
                  <div className={styles.execRight}>
                    {ex.test_case?.ticket_key && (
                      <span className={styles.ticketKey}>{ex.test_case.ticket_key}</span>
                    )}
                    <div className={styles.execBtns}>
                      {["passed", "failed", "blocked", "skipped"].map((s) => (
                        <button
                          key={s}
                          className={`${styles.execBtn} ${ex.status === s ? styles.execBtnActive : ""}`}
                          style={ex.status === s ? { color: EXEC_STATUS_CONFIG[s].color, borderColor: EXEC_STATUS_CONFIG[s].color } : {}}
                          onClick={() => execMut.mutate({ execId: ex.id, status: s })}
                          title={s}
                        >
                          {EXEC_STATUS_CONFIG[s].icon}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    );
  }

  if (isLoading) return <div className={styles.loading}>Loading cycles…</div>;

  return (
    <div>
      <div className={styles.subHeader}>
        <span className={styles.count}>{cycles.length} cycle{cycles.length !== 1 ? "s" : ""}</span>
        <button className={styles.createBtn} onClick={() => setShowCreate(true)}>
          <RiAddLine size={14} /> New Cycle
        </button>
      </div>

      {showCreate && (
        <div className={styles.form}>
          <div className={styles.formTitle}>New Test Cycle</div>
          <input
            className={styles.input}
            placeholder="Cycle name (e.g. Sprint 12 Regression)"
            value={formName}
            onChange={(e) => setFormName(e.target.value)}
          />
          <input
            className={styles.input}
            placeholder="Description (optional)"
            value={formDesc}
            onChange={(e) => setFormDesc(e.target.value)}
          />
          <div className={styles.formActions}>
            <button
              className={styles.saveBtn}
              onClick={() => createMut.mutate()}
              disabled={!formName.trim() || createMut.isPending}
            >
              Create
            </button>
            <button className={styles.cancelBtn} onClick={() => { setShowCreate(false); setFormName(""); setFormDesc(""); }}>Cancel</button>
          </div>
        </div>
      )}

      <div className={styles.cycleGrid}>
        {cycles.map((cycle) => {
          const passedPct = cycle.total > 0 ? Math.round((cycle.passed / cycle.total) * 100) : 0;
          const statusColor = cycle.status === "completed" ? "var(--green)" : cycle.status === "active" ? "var(--accent)" : "var(--text-3)";
          return (
            <div key={cycle.id} className={styles.cycleCard} onClick={() => openCycle(cycle)}>
              <div className={styles.cycleCardTop}>
                <span className={styles.cycleName}>{cycle.name}</span>
                <span className={styles.cycleStatus} style={{ color: statusColor }}>
                  {cycle.status}
                </span>
              </div>
              {cycle.description && <p className={styles.cycleDesc}>{cycle.description}</p>}
              <div className={styles.cycleBar}>
                <div className={styles.cycleBarFill} style={{ width: `${passedPct}%` }} />
              </div>
              <div className={styles.cycleStats}>
                <span className={styles.pillPassed}>{cycle.passed} passed</span>
                <span className={styles.pillFailed}>{cycle.failed} failed</span>
                <span className={styles.pillPending}>{cycle.pending} pending</span>
                <span className={styles.cycleTotalStat}>{cycle.total} total</span>
              </div>
            </div>
          );
        })}
        {cycles.length === 0 && !showCreate && (
          <div className={styles.empty}>No test cycles yet. Create one to start running tests.</div>
        )}
      </div>
    </div>
  );
}

// ── Coverage View ──────────────────────────────────────────────────────────────

function CoverageView({ pod }: { pod: string }) {
  const { data: coverage, isLoading } = useQuery<TestCoverage>({
    queryKey: ["test-coverage", pod],
    queryFn: () => fetchTestCoverage(pod),
    staleTime: 1000 * 60 * 5,
  });

  if (isLoading) return <div className={styles.loading}>EOS analysing coverage…</div>;
  if (!coverage) return <div className={styles.empty}>No coverage data available.</div>;

  const r = (coverage.coverage_pct ?? 0);
  const color = r >= 80 ? "var(--green)" : r >= 50 ? "var(--amber)" : "var(--red)";

  return (
    <div className={styles.coverageView}>
      <div className={styles.coverageHeader}>
        <div className={styles.coverageRing}>
          <svg width={80} height={80} style={{ transform: "rotate(-90deg)" }}>
            <circle cx={40} cy={40} r={34} fill="none" stroke="var(--surface-2)" strokeWidth={6} />
            <circle
              cx={40} cy={40} r={34} fill="none" stroke={color} strokeWidth={6}
              strokeDasharray={2 * Math.PI * 34}
              strokeDashoffset={2 * Math.PI * 34 * (1 - r / 100)}
              strokeLinecap="round"
              style={{ transition: "stroke-dashoffset 0.6s ease" }}
            />
          </svg>
          <span className={styles.coveragePct} style={{ color }}>{r}%</span>
        </div>
        <div className={styles.coverageStats}>
          <div className={styles.coverageStat}>
            <span className={styles.coverageStatVal}>{coverage.total_tickets}</span>
            <span className={styles.coverageStatLabel}>Active Tickets</span>
          </div>
          <div className={styles.coverageStat}>
            <span className={styles.coverageStatVal} style={{ color: "var(--green)" }}>{coverage.tested_tickets}</span>
            <span className={styles.coverageStatLabel}>Tested</span>
          </div>
          <div className={styles.coverageStat}>
            <span className={styles.coverageStatVal} style={{ color: "var(--red)" }}>{coverage.untested_tickets}</span>
            <span className={styles.coverageStatLabel}>Untested</span>
          </div>
        </div>
      </div>

      <div className={styles.eosInsight}>
        <div className={styles.eosInsightHeader}>
          <EOSBadge /> Coverage Insight
        </div>
        <p className={styles.eosInsightText}>{coverage.eos_insight}</p>
      </div>

      {coverage.untested.length > 0 && (
        <div className={styles.untestedSection}>
          <div className={styles.untestedTitle}>Untested Tickets</div>
          <div className={styles.untestedList}>
            {coverage.untested.map((t) => (
              <div key={t.key} className={styles.untestedRow}>
                <span className={styles.ticketKey}>{t.key}</span>
                <span className={styles.untestedSummary}>{t.summary}</span>
                <span
                  className={styles.priorityChip}
                  style={{ color: PRIORITY_COLOR[t.priority?.toLowerCase()] ?? "var(--text-3)" }}
                >
                  {t.priority}
                </span>
                <span className={styles.untestedAssignee}>{t.assignee}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main TestsTab ──────────────────────────────────────────────────────────────

export default function TestsTab({ pod }: { pod: string }) {
  const [subTab, setSubTab] = useState<SubTab>("cases");

  const SUB_TABS: { id: SubTab; label: string; icon: React.ReactNode }[] = [
    { id: "cases",    label: "Test Cases",  icon: <RiTestTubeLine size={14} /> },
    { id: "cycles",   label: "Cycles",      icon: <RiLoopLeftLine size={14} /> },
    { id: "coverage", label: "Coverage",    icon: <RiShieldCheckLine size={14} /> },
  ];

  return (
    <div className={styles.tab}>
      <div className={styles.header}>
        <h3 className={styles.title}>Tests</h3>
        <div className={styles.subTabs}>
          {SUB_TABS.map((t) => (
            <button
              key={t.id}
              className={`${styles.subTabBtn} ${subTab === t.id ? styles.subTabBtnActive : ""}`}
              onClick={() => setSubTab(t.id)}
            >
              {t.icon} {t.label}
            </button>
          ))}
        </div>
      </div>

      {subTab === "cases"    && <TestCasesView pod={pod} />}
      {subTab === "cycles"   && <CyclesView pod={pod} />}
      {subTab === "coverage" && <CoverageView pod={pod} />}
    </div>
  );
}
