import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { fetchTodayStandup, generateStandup, updateStandup } from "@/services/api";
import Skeleton from "@/components/ui/Skeleton";
import styles from "./TodayStandup.module.css";
import { TbRobot } from "react-icons/tb";
import { MdEdit, MdShare, MdAutoAwesome } from "react-icons/md";

export default function TodayStandup() {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<{ yesterday: string; today: string; blockers: string } | null>(null);

  const { data: standup, isLoading, refetch } = useQuery({
    queryKey: ["standup-today"],
    queryFn: fetchTodayStandup,
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => { refetch(); toast.success("Standup generated by EOS"); },
    onError: () => toast.error("Failed to generate standup"),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: number; payload: any }) => updateStandup(id, payload),
    onSuccess: () => { refetch(); setEditing(false); toast.success("Standup updated"); },
  });

  const handleEdit = () => {
    if (!standup) return;
    setDraft({ yesterday: standup.yesterday, today: standup.today, blockers: standup.blockers });
    setEditing(true);
  };

  const handleSave = () => {
    if (!standup || !draft) return;
    updateMut.mutate({ id: standup.id, payload: draft });
  };

  const handleShare = () => {
    if (!standup) return;
    const text = `*Yesterday:* ${standup.yesterday}\n*Today:* ${standup.today}\n*Blockers:* ${standup.blockers || "None"}`;
    navigator.clipboard.writeText(text).then(() => toast.success("Standup copied to clipboard!"));
  };

  if (isLoading) {
    return (
      <div className={styles.card}>
        <div className={styles.header}>
          <span className={styles.icon}><TbRobot /></span>
          <div className="card-title">Today's Standup</div>
          <span className={styles.badge}>EOS</span>
        </div>
        <div className={styles.sections}>
          {[1, 2, 3].map((i) => (
            <div key={i} className={styles.section}>
              <Skeleton width="30%" height={9} />
              <Skeleton width="85%" height={11} />
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className={styles.card}>
      <div className={styles.header}>
        <span className={styles.icon}><TbRobot /></span>
        <div className="card-title">Today's Standup</div>
        <span className={styles.badge}>EOS</span>
        <div className={styles.actions}>
          {standup && !editing && (
            <>
              <button className={`btn btn-ghost btn-xs ${styles.actionBtn}`} onClick={handleEdit}>
                <MdEdit size={13} /> Edit
              </button>
              <button className={`btn btn-ghost btn-xs ${styles.actionBtn}`} onClick={handleShare}>
                <MdShare size={13} /> Share
              </button>
            </>
          )}
          {editing && (
            <>
              <button className={`btn btn-primary btn-xs`} onClick={handleSave} disabled={updateMut.isPending}>
                Save
              </button>
              <button className={`btn btn-ghost btn-xs`} onClick={() => setEditing(false)}>
                Cancel
              </button>
            </>
          )}
        </div>
      </div>

      {!standup ? (
        <div className={styles.noStandup}>
          <div className={styles.noStandupText}>No standup generated yet for today.</div>
          <button
            className={`btn btn-primary btn-sm ${styles.generateBtn}`}
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
          >
            <MdAutoAwesome size={14} />
            {generateMut.isPending ? "Generating…" : "Generate with EOS"}
          </button>
        </div>
      ) : editing && draft ? (
        <div className={styles.editForm}>
          {(["yesterday", "today", "blockers"] as const).map((field) => (
            <div key={field} className={styles.editField}>
              <label className={styles.fieldLabel}>{field.charAt(0).toUpperCase() + field.slice(1)}</label>
              <textarea
                className={styles.textarea}
                value={draft[field]}
                onChange={(e) => setDraft({ ...draft, [field]: e.target.value })}
                rows={2}
                placeholder={field === "blockers" ? "None" : `What did you ${field === "yesterday" ? "do yesterday" : "plan today"}?`}
              />
            </div>
          ))}
        </div>
      ) : (
        <div className={styles.sections}>
          {[
            { label: "Yesterday", value: standup.yesterday, color: "var(--green)" },
            { label: "Today",     value: standup.today,     color: "var(--accent)" },
            { label: "Blockers",  value: standup.blockers || "None", color: standup.blockers ? "var(--red)" : "var(--text-3)" },
          ].map(({ label, value, color }) => (
            <div key={label} className={styles.section}>
              <div className={styles.sectionLabel} style={{ color }}>{label}</div>
              <div className={styles.sectionValue}>{value}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
