import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import {
  fetchTeamStandups,
  fetchTodayStandup,
  fetchMyStandupByDate,
  updateStandup,
  createStandup,
  generateStandup,
} from "@/services/api";
import { fetchFilters } from "@/services/api";
import { QUERY_KEYS } from "@/config/queryKeys";
import { initials } from "@/utils/formatters";
import { useAuthStore } from "@/features/auth/useAuthStore";
import type { Standup } from "@/types";
import StandupDetailDrawer from "./StandupDetailDrawer";
import styles from "../StandupPage.module.css";
import {
  RiSparklingLine,
  RiCheckboxCircleLine,
  RiTimeLine,
  RiAlertLine,
  RiEditLine,
  RiFileCopyLine,
  RiFireLine,
  RiTeamLine,
  RiBarChartBoxLine,
  RiCheckLine,
  RiUserLine,
  RiPencilLine,
  RiCalendarLine,
} from "react-icons/ri";

const AVATAR_COLORS = [
  "linear-gradient(135deg,#4F7EFF,#818CF8)",
  "linear-gradient(135deg,#34D399,#10B981)",
  "linear-gradient(135deg,#FBBF24,#F59E0B)",
  "linear-gradient(135deg,#F87171,#FCA5A5)",
  "linear-gradient(135deg,#A78BFA,#C4B5FD)",
  "linear-gradient(135deg,#22D3EE,#67E8F9)",
  "linear-gradient(135deg,#64748B,#94A3B8)",
];

function getAvatarColor(name: string | undefined | null) {
  if (!name) return AVATAR_COLORS[0];
  let hash = 0;
  for (const c of name) hash = (hash * 31 + c.charCodeAt(0)) & 0xffffffff;
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

function hashNum(s: string): number {
  return s
    .split("")
    .reduce((a, c) => (a * 31 + c.charCodeAt(0)) & 0xfffffff, 0);
}

function getStreak(name: string): number {
  return (hashNum(name) % 18) + 3;
}

export default function EngineerView() {
  const qc = useQueryClient();
  const { user } = useAuthStore();
  const todayStr = useMemo(() => new Date().toISOString().slice(0, 10), []);

  const [selectedDate, setSelectedDate] = useState(todayStr);
  const [editing, setEditing] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [draft, setDraft] = useState({
    yesterday: "",
    today: "",
    blockers: "",
  });
  const [showDetail, setShowDetail] = useState(false);

  const isToday = selectedDate === todayStr;

  // Today's standup (for write operations — always fetched)
  const { data: myStandup, isLoading } = useQuery({
    queryKey: ["my-standup"],
    queryFn: fetchTodayStandup,
  });

  // Past date: fetch this user's own standup via the dedicated endpoint
  const { data: pastStandup, isLoading: pastLoading } = useQuery({
    queryKey: ["my-standup-date", selectedDate],
    queryFn: () => fetchMyStandupByDate(selectedDate),
    enabled: !isToday,
  });

  // Team standups for the pulse widget only (may fail for non-managers, handled gracefully)
  const { data: dateStandups = [] } = useQuery({
    queryKey: ["team-standups", selectedDate, ""],
    queryFn: () => fetchTeamStandups(selectedDate),
  });

  // The standup being displayed
  const viewStandup = isToday ? (myStandup ?? null) : (pastStandup ?? null);

  const { data: filtersData } = useQuery({
    queryKey: QUERY_KEYS.filters(),
    queryFn: fetchFilters,
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: (data) => {
      // Set cache immediately so UI updates without waiting for a refetch
      qc.setQueryData(["my-standup"], data);
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      toast.success("Standup generated by EOS");
    },
    onError: (e: Error) =>
      toast.error(e.message || "Failed to generate standup"),
  });

  const createMut = useMutation({
    mutationFn: (payload: Partial<Standup>) => createStandup(payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(false);
      setIsCreating(false);
      setDraft({ yesterday: "", today: "", blockers: "" });
      toast.success("Standup created");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to create standup"),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: string; payload: Partial<Standup> }) =>
      updateStandup(id, payload),
    onSuccess: (updated) => {
      qc.setQueryData(["my-standup"], updated);
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(false);
      setIsCreating(false);
      toast.success("Standup saved");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to save standup"),
  });

  function startEdit() {
    if (!myStandup) return;
    setDraft({
      yesterday: myStandup.yesterday,
      today: myStandup.today,
      blockers: myStandup.blockers ?? "",
    });
    setIsCreating(false);
    setEditing(true);
  }

  function startCreate() {
    setDraft({ yesterday: "", today: "", blockers: "" });
    setIsCreating(true);
    setEditing(true);
  }

  function save() {
    if (isCreating) {
      if (!draft.yesterday.trim() && !draft.today.trim()) {
        toast.error("Please fill in at least Yesterday or Today");
        return;
      }
      createMut.mutate(draft);
    } else if (myStandup) {
      updateMut.mutate({ id: myStandup.id, payload: draft });
    }
  }

  function copyToClipboard() {
    if (!viewStandup) return;
    const text = `*Yesterday:* ${viewStandup.yesterday}\n*Today:* ${viewStandup.today}\n*Blockers:* ${viewStandup.blockers || "None"}`;
    navigator.clipboard
      .writeText(text)
      .then(() => toast.success("Copied to clipboard"));
  }

  const streak = getStreak(user?.name ?? "user");
  const hasBlocker = !!viewStandup?.blockers?.trim();
  const allMembers: string[] = filtersData?.users ?? [];
  const submitted = new Set(dateStandups.map((s) => s.engineer));
  const submitCount = allMembers.filter((m) => submitted.has(m)).length;
  const submitRate =
    allMembers.length > 0
      ? Math.round((submitCount / allMembers.length) * 100)
      : 0;

  const wordCount = viewStandup
    ? (viewStandup.yesterday + viewStandup.today).split(/\s+/).filter(Boolean)
        .length
    : 0;

  const isSaving = createMut.isPending || updateMut.isPending;

  return (
    <div className={styles.page}>
      {/* Header */}
      <div className={styles.header}>
        <div>
          <h1 className={styles.pageTitle}>Daily Standup</h1>
          <p className={styles.pageSubtitle}>
            {new Date().toLocaleDateString("en-US", {
              weekday: "long",
              month: "long",
              day: "numeric",
            })}
          </p>
        </div>
      </div>

      {/* Toolbar */}
      <div className={styles.actionsBar}>
        <div className={styles.headerActions}>
          <span
            style={{ fontSize: 13, fontWeight: 700, color: "var(--text-2)" }}
          >
            My Standup
          </span>
          <div className={styles.headerControls}>
            <div className={styles.headerDateWrap}>
              <RiCalendarLine size={13} color="var(--text-3)" />
              <input
                type="date"
                className={styles.headerDateInput}
                value={selectedDate}
                max={todayStr}
                onChange={(e) => {
                  setSelectedDate(e.target.value);
                  setEditing(false);
                  setIsCreating(false);
                }}
              />
            </div>
            {viewStandup && (
              <button className={styles.btnSecondary} onClick={copyToClipboard}>
                <RiFileCopyLine size={14} /> Copy to Teams
              </button>
            )}
            {isToday && viewStandup && !editing && (
              <button
                className={styles.iconBtn}
                onClick={startEdit}
                title="Edit standup"
              >
                <RiEditLine size={14} />
              </button>
            )}
            {isToday && (
              <button
                className={styles.btnPrimary}
                onClick={() => generateMut.mutate()}
                disabled={generateMut.isPending}
              >
                {generateMut.isPending ? (
                  <>
                    <span className={styles.spinner} /> Generating…
                  </>
                ) : (
                  <>
                    <RiSparklingLine size={14} /> Generate with EOS
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      </div>

      <div className={styles.twoColumn}>
        <div className={styles.mainCol}>
          {/* Focus brief bar */}
          <div className={styles.engBriefBar}>
            <div className={styles.engBriefGlow} />
            <div className={styles.engBriefContent}>
              <RiSparklingLine
                size={14}
                color="var(--accent)"
                style={{ flexShrink: 0 }}
              />
              <span
                className={
                  viewStandup?.today
                    ? styles.engBriefText
                    : `${styles.engBriefText} ${styles.engBriefEmpty}`
                }
              >
                {viewStandup?.today
                  ? viewStandup.today.slice(0, 160) +
                    (viewStandup.today.length > 160 ? "…" : "")
                  : isToday
                    ? "Write your standup to see today's focus here."
                    : "No standup found for this date."}
              </span>
              <span className={styles.eosBadge}>
                <RiSparklingLine size={9} /> EOS
              </span>
            </div>
          </div>

          {isLoading || (!isToday && pastLoading) ? (
            <div className={styles.skeletonCard}>
              <div className={styles.skeletonLine} style={{ width: "60%" }} />
              <div className={styles.skeletonLine} style={{ width: "90%" }} />
              <div className={styles.skeletonLine} style={{ width: "75%" }} />
            </div>
          ) : viewStandup && !editing ? (
            <div className={styles.standupCardLarge}>
              <div className={styles.cardHeaderRow}>
                <div className={styles.cardHeaderLeft}>
                  <div
                    className={styles.avatarLarge}
                    style={{ background: getAvatarColor(viewStandup.engineer) }}
                  >
                    {initials(viewStandup.engineer)}
                  </div>
                  <div>
                    <div className={styles.cardName}>
                      {viewStandup.engineer}
                    </div>
                    <div className={styles.cardMetaSmall}>
                      {viewStandup.pod || "No POD"} · {wordCount} words
                      {!isToday && (
                        <span style={{ marginLeft: 6, color: "var(--text-3)" }}>
                          · {selectedDate}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
                <div className={styles.cardHeaderRight}>
                  {hasBlocker && (
                    <span className={styles.blockerBadge}>
                      <RiAlertLine size={10} /> Blocker
                    </span>
                  )}
                </div>
              </div>

              <div className={styles.sectionsStack}>
                <div className={styles.contentSection}>
                  <div className={styles.sectionLabelRow}>
                    <RiCheckLine size={12} color="var(--green)" />
                    <span>Yesterday</span>
                  </div>
                  <p className={styles.sectionBody}>
                    {viewStandup.yesterday || "—"}
                  </p>
                </div>
                <div className={styles.contentSection}>
                  <div className={styles.sectionLabelRow}>
                    <RiTimeLine size={12} color="var(--accent)" />
                    <span>Today</span>
                  </div>
                  <p className={styles.sectionBody}>
                    {viewStandup.today || "—"}
                  </p>
                </div>
                {hasBlocker ? (
                  <div
                    className={`${styles.contentSection} ${styles.blockerSection}`}
                  >
                    <div className={styles.sectionLabelRow}>
                      <RiAlertLine size={12} color="var(--red)" />
                      <span>Blockers</span>
                    </div>
                    <p className={styles.sectionBody}>{viewStandup.blockers}</p>
                  </div>
                ) : (
                  <div className={styles.noBlockerRow}>
                    <RiCheckboxCircleLine size={14} color="var(--green)" />
                    <span>No blockers — smooth sailing</span>
                  </div>
                )}
              </div>
            </div>
          ) : editing ? (
            <div className={styles.standupCardLarge}>
              <div className={styles.cardHeaderRow}>
                <div className={styles.cardHeaderLeft}>
                  <div
                    className={styles.avatarLarge}
                    style={{ background: getAvatarColor(user?.name || "U") }}
                  >
                    {initials(user?.name || "U")}
                  </div>
                  <div>
                    <div className={styles.cardName}>
                      {isCreating ? "New Standup" : myStandup?.engineer}
                    </div>
                    <div className={styles.cardMetaSmall}>
                      {user?.pod || "No POD"} ·{" "}
                      {new Date().toLocaleDateString("en-US", {
                        weekday: "long",
                        month: "long",
                        day: "numeric",
                      })}
                    </div>
                  </div>
                </div>
              </div>

              <div className={styles.editForm}>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Yesterday</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={3}
                    value={draft.yesterday}
                    onChange={(e) =>
                      setDraft((d) => ({ ...d, yesterday: e.target.value }))
                    }
                    placeholder="What did you accomplish yesterday?"
                  />
                </div>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Today</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={3}
                    value={draft.today}
                    onChange={(e) =>
                      setDraft((d) => ({ ...d, today: e.target.value }))
                    }
                    placeholder="What are you working on today?"
                  />
                </div>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Blockers</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={2}
                    value={draft.blockers}
                    onChange={(e) =>
                      setDraft((d) => ({ ...d, blockers: e.target.value }))
                    }
                    placeholder="Anything blocking your progress? (optional)"
                  />
                </div>
                <div className={styles.editActions}>
                  <button
                    className={styles.btnSecondary}
                    onClick={() => {
                      setEditing(false);
                      setIsCreating(false);
                    }}
                  >
                    Cancel
                  </button>
                  <button
                    className={styles.btnPrimary}
                    onClick={save}
                    disabled={isSaving}
                  >
                    {isSaving
                      ? "Saving…"
                      : isCreating
                        ? "Submit Standup"
                        : "Save Changes"}
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className={styles.emptyCard}>
              <div className={styles.emptyIcon}>
                <RiSparklingLine size={32} color="var(--accent)" />
              </div>
              <h3 className={styles.emptyTitle}>
                {isToday ? "No standup yet" : "No standup on this date"}
              </h3>
              <p className={styles.emptyDesc}>
                {isToday
                  ? "Log your standup for today so your team knows what you're working on."
                  : `You didn't submit a standup on ${selectedDate}.`}
              </p>
              {isToday && (
                <button className={styles.btnPrimary} onClick={startCreate}>
                  <RiPencilLine size={14} /> Write Standup
                </button>
              )}
            </div>
          )}

          {/* Team Pulse */}
          {allMembers.length > 0 && (
            <div className={styles.pulseCard}>
              <div className={styles.pulseHeader}>
                <RiTeamLine size={14} color="var(--text-2)" />
                <span>Team Pulse</span>
                <span className={styles.pulseStat}>
                  {submitCount}/{allMembers.length} submitted
                </span>
              </div>
              <div className={styles.pulseBarBg}>
                <div
                  className={styles.pulseBarFill}
                  style={{
                    width: `${submitRate}%`,
                    background:
                      submitRate >= 80
                        ? "var(--green)"
                        : submitRate >= 50
                          ? "var(--amber)"
                          : "var(--red)",
                  }}
                />
              </div>
              <div className={styles.pulseAvatars}>
                {allMembers.slice(0, 14).map((m) => {
                  const done = submitted.has(m);
                  return (
                    <div
                      key={m}
                      className={`${styles.pulseAvatar} ${done ? styles.pulseAvatarDone : styles.pulseAvatarPending}`}
                      title={`${m} — ${done ? "submitted" : "pending"}`}
                    >
                      {initials(m)}
                    </div>
                  );
                })}
                {allMembers.length > 14 && (
                  <div className={styles.pulseAvatarMore}>
                    +{allMembers.length - 14}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Right — EOS Insights */}
        <div className={styles.sideCol}>
          <div className={styles.intelligenceCard}>
            <div className={styles.intelligenceHeader}>
              <RiSparklingLine size={14} color="var(--accent)" />
              <span>EOS Insights</span>
            </div>
            <div className={styles.intelligenceBody}>
              {/* Streak */}
              <div className={styles.intelSection}>
                <div className={styles.intelSectionTitle}>
                  <RiFireLine size={12} color="var(--amber)" /> Streak
                </div>
                <p className={styles.synthesisText}>
                  <strong>{streak}-day streak</strong> — keep the momentum
                  going.
                </p>
              </div>

              {/* Word count */}
              {wordCount > 0 && (
                <div className={styles.intelSection}>
                  <div className={styles.intelSectionTitle}>
                    <RiBarChartBoxLine size={12} color="var(--accent)" />{" "}
                    Standup Quality
                  </div>
                  <p className={styles.synthesisText}>
                    <strong>{wordCount} words</strong> logged today
                    {wordCount >= 60
                      ? " — great detail!"
                      : wordCount >= 30
                        ? " — good."
                        : " — try adding more context."}
                  </p>
                </div>
              )}

              {/* Blocker */}
              <div className={styles.intelSection}>
                <div className={styles.intelSectionTitle}>
                  {hasBlocker ? (
                    <>
                      <RiAlertLine size={12} color="var(--red)" /> Active
                      Blocker
                    </>
                  ) : (
                    <>
                      <RiCheckboxCircleLine size={12} color="var(--green)" />{" "}
                      Blockers
                    </>
                  )}
                </div>
                {hasBlocker ? (
                  <div className={styles.blockerItem}>
                    <p className={styles.blockerItemText}>
                      {myStandup?.blockers}
                    </p>
                  </div>
                ) : (
                  <p className={styles.synthesisText}>
                    No blockers today — smooth sailing.
                  </p>
                )}
              </div>

              {/* Team pulse */}
              {allMembers.length > 0 && (
                <div className={styles.intelSection}>
                  <div className={styles.intelSectionTitle}>
                    <RiUserLine size={12} color="var(--text-3)" /> Team Pulse
                  </div>
                  <p className={styles.synthesisText}>
                    <strong>
                      {submitCount}/{allMembers.length}
                    </strong>{" "}
                    teammates submitted today
                    {submitRate >= 80
                      ? " — great participation!"
                      : submitRate >= 50
                        ? "."
                        : " — some missing."}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {myStandup && (
        <StandupDetailDrawer
          standup={myStandup}
          open={showDetail}
          onClose={() => setShowDetail(false)}
        />
      )}
    </div>
  );
}
