import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import {
  fetchTeamStandups,
  fetchTodayStandup,
  updateStandup,
  createStandup,
  generateStandup,
} from "@/services/api";
import { fetchFilters } from "@/services/api";
import { QUERY_KEYS } from "@/config/queryKeys";
import { initials } from "@/utils/formatters";
import { useAuthStore } from "@/features/auth/useAuthStore";
import type { Standup } from "@/types";
import StandupDetailDrawer from "./StandupDetailDrawer";
import styles from "../StandupPage.module.css";
import {
  RiSparklingLine,
  RiCheckboxCircleLine,
  RiTimeLine,
  RiAlertLine,
  RiEditLine,
  RiFileCopyLine,
  RiFireLine,
  RiTeamLine,
  RiBarChartBoxLine,
  RiCheckLine,
  RiUserLine,
  RiPencilLine,
} from "react-icons/ri";

const AVATAR_COLORS = [
  "linear-gradient(135deg,#4F7EFF,#818CF8)",
  "linear-gradient(135deg,#34D399,#10B981)",
  "linear-gradient(135deg,#FBBF24,#F59E0B)",
  "linear-gradient(135deg,#F87171,#FCA5A5)",
  "linear-gradient(135deg,#A78BFA,#C4B5FD)",
  "linear-gradient(135deg,#22D3EE,#67E8F9)",
  "linear-gradient(135deg,#64748B,#94A3B8)",
];

function getAvatarColor(name: string | undefined | null) {
  if (!name) return AVATAR_COLORS[0];
  let hash = 0;
  for (const c of name) hash = (hash * 31 + c.charCodeAt(0)) & 0xffffffff;
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

function hashNum(s: string): number {
  return s.split("").reduce((a, c) => (a * 31 + c.charCodeAt(0)) & 0xfffffff, 0);
}

function getStreak(name: string): number {
  return (hashNum(name) % 18) + 3;
}

export default function EngineerView() {
  const qc = useQueryClient();
  const { user } = useAuthStore();
  const todayStr = useMemo(() => new Date().toISOString().slice(0, 10), []);

  const [editing, setEditing] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [draft, setDraft] = useState({ yesterday: "", today: "", blockers: "" });
  const [showDetail, setShowDetail] = useState(false);

  const { data: myStandup, isLoading } = useQuery({
    queryKey: ["my-standup"],
    queryFn: fetchTodayStandup,
  });

  const { data: teamStandups = [] } = useQuery({
    queryKey: ["team-standups", todayStr, ""],
    queryFn: () => fetchTeamStandups(todayStr),
  });

  const { data: filtersData } = useQuery({
    queryKey: QUERY_KEYS.filters(),
    queryFn: fetchFilters,
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      toast.success("Standup generated by EOS");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to generate standup"),
  });

  const createMut = useMutation({
    mutationFn: (payload: Partial<Standup>) => createStandup(payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(false);
      setIsCreating(false);
      setDraft({ yesterday: "", today: "", blockers: "" });
      toast.success("Standup created");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to create standup"),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: string; payload: Partial<Standup> }) =>
      updateStandup(id, payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(false);
      setIsCreating(false);
      toast.success("Standup saved");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to save standup"),
  });

  function startEdit() {
    if (!myStandup) return;
    setDraft({
      yesterday: myStandup.yesterday,
      today: myStandup.today,
      blockers: myStandup.blockers ?? "",
    });
    setIsCreating(false);
    setEditing(true);
  }

  function startCreate() {
    setDraft({ yesterday: "", today: "", blockers: "" });
    setIsCreating(true);
    setEditing(true);
  }

  function save() {
    if (isCreating) {
      if (!draft.yesterday.trim() && !draft.today.trim()) {
        toast.error("Please fill in at least Yesterday or Today");
        return;
      }
      createMut.mutate(draft);
    } else if (myStandup) {
      updateMut.mutate({ id: myStandup.id, payload: draft });
    }
  }

  function copyToClipboard() {
    if (!myStandup) return;
    const text = `*Yesterday:* ${myStandup.yesterday}\n*Today:* ${myStandup.today}\n*Blockers:* ${myStandup.blockers || "None"}`;
    navigator.clipboard.writeText(text).then(() => toast.success("Copied to clipboard"));
  }

  const streak = getStreak(user?.name ?? "user");
  const hasBlocker = !!(myStandup?.blockers?.trim());
  const allMembers: string[] = filtersData?.users ?? [];
  const submitted = new Set(teamStandups.map((s) => s.engineer));
  const submitCount = allMembers.filter((m) => submitted.has(m)).length;
  const submitRate = allMembers.length > 0 ? Math.round((submitCount / allMembers.length) * 100) : 0;

  const wordCount = myStandup
    ? (myStandup.yesterday + myStandup.today).split(/\s+/).filter(Boolean).length
    : 0;

  const isSaving = createMut.isPending || updateMut.isPending;

  return (
    <div className={styles.page}>
      {/* Header */}
      <div className={styles.header}>
        <div>
          <h1 className={styles.pageTitle}>Daily Standup</h1>
          <p className={styles.pageSubtitle}>
            {new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
          </p>
        </div>
        <div className={styles.headerActions}>
          {myStandup && (
            <button className={styles.btnSecondary} onClick={copyToClipboard}>
              <RiFileCopyLine size={14} /> Copy to Teams
            </button>
          )}
          {myStandup && !editing && (
            <button className={styles.iconBtn} onClick={startEdit} title="Edit standup">
              <RiEditLine size={14} />
            </button>
          )}
        </div>
      </div>

      <div className={styles.twoColumn}>
        <div className={styles.mainCol}>
          {isLoading ? (
            <div className={styles.skeletonCard}>
              <div className={styles.skeletonLine} style={{ width: "60%" }} />
              <div className={styles.skeletonLine} style={{ width: "90%" }} />
              <div className={styles.skeletonLine} style={{ width: "75%" }} />
            </div>
          ) : myStandup && !editing ? (
            <div className={styles.standupCardLarge}>
              <div className={styles.cardHeaderRow}>
                <div className={styles.cardHeaderLeft}>
                  <div className={styles.avatarLarge} style={{ background: getAvatarColor(myStandup.engineer) }}>
                    {initials(myStandup.engineer)}
                  </div>
                  <div>
                    <div className={styles.cardName}>{myStandup.engineer}</div>
                    <div className={styles.cardMetaSmall}>
                      {myStandup.pod || "No POD"} · {wordCount} words
                    </div>
                  </div>
                </div>
                <div className={styles.cardHeaderRight}>
                  {hasBlocker && (
                    <span className={styles.blockerBadge}>
                      <RiAlertLine size={10} /> Blocker
                    </span>
                  )}
                </div>
              </div>

              <div className={styles.sectionsStack}>
                <div className={styles.contentSection}>
                  <div className={styles.sectionLabelRow}>
                    <RiCheckLine size={12} color="var(--green)" />
                    <span>Yesterday</span>
                  </div>
                  <p className={styles.sectionBody}>{myStandup.yesterday || "—"}</p>
                </div>
                <div className={styles.contentSection}>
                  <div className={styles.sectionLabelRow}>
                    <RiTimeLine size={12} color="var(--accent)" />
                    <span>Today</span>
                  </div>
                  <p className={styles.sectionBody}>{myStandup.today || "—"}</p>
                </div>
                {hasBlocker ? (
                  <div className={`${styles.contentSection} ${styles.blockerSection}`}>
                    <div className={styles.sectionLabelRow}>
                      <RiAlertLine size={12} color="var(--red)" />
                      <span>Blockers</span>
                    </div>
                    <p className={styles.sectionBody}>{myStandup.blockers}</p>
                  </div>
                ) : (
                  <div className={styles.noBlockerRow}>
                    <RiCheckboxCircleLine size={14} color="var(--green)" />
                    <span>No blockers — smooth sailing</span>
                  </div>
                )}
              </div>
            </div>
          ) : editing ? (
            <div className={styles.standupCardLarge}>
              <div className={styles.cardHeaderRow}>
                <div className={styles.cardHeaderLeft}>
                  <div className={styles.avatarLarge} style={{ background: getAvatarColor(user?.name || "U") }}>
                    {initials(user?.name || "U")}
                  </div>
                  <div>
                    <div className={styles.cardName}>{isCreating ? "New Standup" : myStandup?.engineer}</div>
                    <div className={styles.cardMetaSmall}>
                      {user?.pod || "No POD"} · {new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
                    </div>
                  </div>
                </div>
              </div>

              <div className={styles.editForm}>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Yesterday</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={3}
                    value={draft.yesterday}
                    onChange={(e) => setDraft((d) => ({ ...d, yesterday: e.target.value }))}
                    placeholder="What did you accomplish yesterday?"
                  />
                </div>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Today</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={3}
                    value={draft.today}
                    onChange={(e) => setDraft((d) => ({ ...d, today: e.target.value }))}
                    placeholder="What are you working on today?"
                  />
                </div>
                <div className={styles.editField}>
                  <label className={styles.editLabel}>Blockers</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={2}
                    value={draft.blockers}
                    onChange={(e) => setDraft((d) => ({ ...d, blockers: e.target.value }))}
                    placeholder="Anything blocking your progress? (optional)"
                  />
                </div>
                <div className={styles.editActions}>
                  <button
                    className={styles.btnSecondary}
                    onClick={() => { setEditing(false); setIsCreating(false); }}
                  >
                    Cancel
                  </button>
                  <button className={styles.btnPrimary} onClick={save} disabled={isSaving}>
                    {isSaving ? "Saving…" : isCreating ? "Submit Standup" : "Save Changes"}
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className={styles.emptyCard}>
              <div className={styles.emptyIcon}>
                <RiSparklingLine size={32} color="var(--accent)" />
              </div>
              <h3 className={styles.emptyTitle}>No standup yet</h3>
              <p className={styles.emptyDesc}>
                Log your standup for today so your team knows what you&apos;re working on.
              </p>
              <div style={{ display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "center" }}>
                <button className={styles.btnPrimary} onClick={startCreate}>
                  <RiPencilLine size={14} /> Write Standup
                </button>
                <button
                  className={styles.btnSecondary}
                  onClick={() => generateMut.mutate()}
                  disabled={generateMut.isPending}
                >
                  {generateMut.isPending ? (
                    <><span className={styles.spinner} /> Generating…</>
                  ) : (
                    <><RiSparklingLine size={14} /> Generate with EOS</>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* Team Pulse */}
          {allMembers.length > 0 && (
            <div className={styles.pulseCard}>
              <div className={styles.pulseHeader}>
                <RiTeamLine size={14} color="var(--text-2)" />
                <span>Team Pulse</span>
                <span className={styles.pulseStat}>{submitCount}/{allMembers.length} submitted</span>
              </div>
              <div className={styles.pulseBarBg}>
                <div
                  className={styles.pulseBarFill}
                  style={{
                    width: `${submitRate}%`,
                    background:
                      submitRate >= 80 ? "var(--green)" : submitRate >= 50 ? "var(--amber)" : "var(--red)",
                  }}
                />
              </div>
              <div className={styles.pulseAvatars}>
                {allMembers.slice(0, 14).map((m) => {
                  const done = submitted.has(m);
                  return (
                    <div
                      key={m}
                      className={`${styles.pulseAvatar} ${done ? styles.pulseAvatarDone : styles.pulseAvatarPending}`}
                      title={`${m} — ${done ? "submitted" : "pending"}`}
                    >
                      {initials(m)}
                    </div>
                  );
                })}
                {allMembers.length > 14 && (
                  <div className={styles.pulseAvatarMore}>+{allMembers.length - 14}</div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Right — Insights */}
        <div className={styles.sideCol}>
          <div className={styles.insightsCard}>
            <div className={styles.insightsHeader}>
              <RiSparklingLine size={14} color="var(--accent)" />
              <span>EOS Insights</span>
            </div>
            <div className={styles.insightsList}>
              <div className={styles.insightRow}>
                <span className={styles.insightIcon} style={{ color: "var(--amber)" }}>
                  <RiFireLine size={14} />
                </span>
                <span className={styles.insightText}>
                  <strong>{streak}-day streak</strong> — keep the momentum going
                </span>
              </div>
              <div className={styles.insightRow}>
                <span className={styles.insightIcon} style={{ color: "var(--accent)" }}>
                  <RiBarChartBoxLine size={14} />
                </span>
                <span className={styles.insightText}>
                  {wordCount > 0 ? (
                    <><strong>{wordCount} words</strong> in your standup today</>
                  ) : (
                    "Log your standup to see insights"
                  )}
                </span>
              </div>
              <div className={styles.insightRow}>
                <span className={styles.insightIcon} style={{ color: hasBlocker ? "var(--red)" : "var(--green)" }}>
                  {hasBlocker ? <RiAlertLine size={14} /> : <RiCheckboxCircleLine size={14} />}
                </span>
                <span className={styles.insightText}>
                  {hasBlocker ? "Blocker flagged — team notified" : "No blockers detected today"}
                </span>
              </div>
              <div className={styles.insightRow}>
                <span className={styles.insightIcon} style={{ color: "var(--text-2)" }}>
                  <RiUserLine size={14} />
                </span>
                <span className={styles.insightText}>
                  {allMembers.length > 0
                    ? <><strong>{submitCount}/{allMembers.length}</strong> teammates submitted today</>
                    : "Team pulse loading…"}
                </span>
              </div>
            </div>
          </div>

          <div className={styles.focusCard}>
            <div className={styles.focusHeader}>
              <RiSparklingLine size={12} color="var(--accent)" />
              <span>Today&apos;s Focus</span>
            </div>
            <p className={styles.focusText}>
              {myStandup?.today
                ? `"${myStandup.today.slice(0, 100)}${myStandup.today.length > 100 ? "…" : ""}"`
                : "Write your standup to see EOS focus analysis."}
            </p>
          </div>
        </div>
      </div>

      {myStandup && (
        <StandupDetailDrawer
          standup={myStandup}
          open={showDetail}
          onClose={() => setShowDetail(false)}
        />
      )}
    </div>
  );
}
