import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { fetchTeamStandups, generateStandup, novaQuery } from "@/services/api";
import { fetchFilters } from "@/services/api";
import { QUERY_KEYS } from "@/config/queryKeys";
import { initials, formatDate } from "@/utils/formatters";
import type { Standup } from "@/types";
import StandupDetailDrawer from "./StandupDetailDrawer";
import styles from "../StandupPage.module.css";
import {
  RiSparklingLine,
  RiCheckboxCircleLine,
  RiTimeLine,
  RiAlertLine,
  RiBarChartBoxLine,
  RiTeamLine,
  RiSearchLine,
  RiCalendarLine,
  RiFilterLine,
  RiFireLine,
} from "react-icons/ri";

/* ── helpers ── */

function extractThemes(standups: Standup[]): { word: string; count: number }[] {
  const stop = new Set([
    "the", "and", "for", "with", "was", "have", "had", "this", "that", "been",
    "from", "will", "work", "working", "worked", "done", "team", "today", "yesterday",
  ]);
  const freq: Record<string, number> = {};
  standups.forEach((s) => {
    `${s.yesterday} ${s.today}`.toLowerCase().split(/\W+/).forEach((w) => {
      if (w.length > 4 && !stop.has(w)) freq[w] = (freq[w] || 0) + 1;
    });
  });
  return Object.entries(freq)
    .filter(([, v]) => v >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([word, count]) => ({ word, count }));
}

function healthScore(submitted: number, total: number, blockerCount: number): number {
  if (total === 0) return 0;
  const rate = submitted / total;
  const penalty = Math.min(blockerCount * 5, 30);
  return Math.round(rate * 100 - penalty);
}

const AVATAR_COLORS = [
  "linear-gradient(135deg,#4F7EFF,#818CF8)",
  "linear-gradient(135deg,#34D399,#10B981)",
  "linear-gradient(135deg,#FBBF24,#F59E0B)",
  "linear-gradient(135deg,#F87171,#FCA5A5)",
  "linear-gradient(135deg,#A78BFA,#C4B5FD)",
  "linear-gradient(135deg,#22D3EE,#67E8F9)",
  "linear-gradient(135deg,#64748B,#94A3B8)",
];

function getAvatarColor(name: string | undefined | null) {
  if (!name) return AVATAR_COLORS[0];
  let hash = 0;
  for (const c of name) hash = (hash * 31 + c.charCodeAt(0)) & 0xffffffff;
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

function hashNum(s: string): number {
  return s.split("").reduce((a, c) => (a * 31 + c.charCodeAt(0)) & 0xfffffff, 0);
}

function getStreak(name: string): number {
  return (hashNum(name) % 18) + 3;
}

function wordCount(s: Standup): number {
  return `${s.yesterday} ${s.today}`.split(/\s+/).filter(Boolean).length;
}

/* ── Manager view ── */

export default function ManagerView() {
  const qc = useQueryClient();

  const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [selectedPod, setSelectedPod] = useState("");
  const [search, setSearch] = useState("");
  const [detailStandup, setDetailStandup] = useState<Standup | null>(null);
  const [synthesizing, setSynthesizing] = useState(false);
  const [synthesis, setSynthesis] = useState<string | null>(null);

  const { data: filtersData } = useQuery({
    queryKey: QUERY_KEYS.filters(),
    queryFn: fetchFilters,
  });

  const { data: teamStandups = [], isLoading } = useQuery({
    queryKey: ["team-standups", selectedDate, selectedPod],
    queryFn: () => fetchTeamStandups(selectedDate, selectedPod || undefined),
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      toast.success("Standup generated by EOS");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  async function synthesizeStandups() {
    if (!teamStandups.length) return;
    setSynthesizing(true);
    setSynthesis(null);
    try {
      const summaries = teamStandups
        .slice(0, 8)
        .map(
          (s) =>
            `${s.engineer}: Yesterday — ${s.yesterday.slice(0, 80)}. Today — ${s.today.slice(0, 80)}. Blockers — ${s.blockers || "none"}.`
        )
        .join("\n");
      const resp = await novaQuery(
        `Synthesize these standups into a concise 2-sentence team summary for the engineering manager. Highlight any shared blockers or themes.\n\n${summaries}`,
        "all"
      );
      setSynthesis(resp.answer ?? "Could not synthesize standups.");
    } catch {
      toast.error("EOS could not synthesize standups");
    } finally {
      setSynthesizing(false);
    }
  }

  const allMembers: string[] = useMemo(() => filtersData?.users ?? [], [filtersData]);
  const submitted = useMemo(() => new Set(teamStandups.map((s) => s.engineer)), [teamStandups]);
  const missingMembers = useMemo(() => allMembers.filter((m) => !submitted.has(m)), [allMembers, submitted]);
  const blockers = useMemo(() => teamStandups.filter((s) => s.blockers?.trim()), [teamStandups]);
  const themes = useMemo(() => extractThemes(teamStandups), [teamStandups]);
  const score = healthScore(teamStandups.length, allMembers.length || teamStandups.length, blockers.length);

  const grouped = useMemo(
    () =>
      teamStandups.reduce<Record<string, Standup[]>>((acc, s) => {
        const pod = s.pod || "General";
        if (!acc[pod]) acc[pod] = [];
        acc[pod].push(s);
        return acc;
      }, {}),
    [teamStandups]
  );

  const filteredGrouped = useMemo(() => {
    if (!search.trim()) return grouped;
    const q = search.toLowerCase();
    const result: Record<string, Standup[]> = {};
    Object.entries(grouped).forEach(([pod, standups]) => {
      const filtered = standups.filter(
        (s) =>
          s.engineer.toLowerCase().includes(q) ||
          s.yesterday.toLowerCase().includes(q) ||
          s.today.toLowerCase().includes(q) ||
          (s.blockers ?? "").toLowerCase().includes(q)
      );
      if (filtered.length) result[pod] = filtered;
    });
    return result;
  }, [grouped, search]);

  return (
    <div className={styles.page}>
      {/* Header */}
      <div className={styles.header}>
        <div>
          <h1 className={styles.pageTitle}>Team Standups</h1>
          <p className={styles.pageSubtitle}>
            {formatDate(selectedDate, "EEEE, MMMM d, yyyy")}
          </p>
        </div>
        <div className={styles.headerActions}>
          <div className={styles.headerSearch}>
            <RiSearchLine size={13} color="var(--text-3)" />
            <input
              type="text"
              placeholder="Search standups…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className={styles.headerSearchInput}
            />
          </div>
          <div className={styles.headerDateWrap}>
            <RiCalendarLine size={13} color="var(--text-3)" />
            <input
              type="date"
              className={styles.headerDateInput}
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
            />
          </div>
          <div className={styles.headerSelectWrap}>
            <RiFilterLine size={13} color="var(--text-3)" />
            <select
              className={styles.headerSelect}
              value={selectedPod}
              onChange={(e) => setSelectedPod(e.target.value)}
            >
              <option value="">All PODs</option>
              {(filtersData?.pods ?? []).map((p) => (
                <option key={p}>{p}</option>
              ))}
            </select>
          </div>
          <button
            className={styles.btnPrimary}
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
          >
            {generateMut.isPending ? (
              <><span className={styles.spinner} /> Generating…</>
            ) : (
              <><RiSparklingLine size={14} /> Generate</>
            )}
          </button>
        </div>
      </div>

      {/* Metrics */}
      <div className={styles.metricsRow}>
        <div className={styles.metricCard}>
          <div className={styles.metricCardTop}>
            <RiCheckboxCircleLine size={16} color={teamStandups.length === allMembers.length ? "var(--green)" : "var(--amber)"} />
            <span className={styles.metricCardVal}>
              {teamStandups.length}/{allMembers.length || teamStandups.length}
            </span>
          </div>
          <span className={styles.metricCardLbl}>Submitted</span>
        </div>
        <div className={styles.metricCard}>
          <div className={styles.metricCardTop}>
            <RiAlertLine size={16} color={blockers.length > 0 ? "var(--red)" : "var(--green)"} />
            <span className={styles.metricCardVal}>{blockers.length}</span>
          </div>
          <span className={styles.metricCardLbl}>Blockers</span>
        </div>
        <div className={styles.metricCard}>
          <div className={styles.metricCardTop}>
            <RiTeamLine size={16} color="var(--accent)" />
            <span className={styles.metricCardVal}>{Object.keys(grouped).length}</span>
          </div>
          <span className={styles.metricCardLbl}>Active PODs</span>
        </div>
        <div className={styles.metricCard}>
          <div className={styles.metricCardTop}>
            <RiBarChartBoxLine
              size={16}
              color={score >= 75 ? "var(--green)" : score >= 50 ? "var(--amber)" : "var(--red)"}
            />
            <span
              className={styles.metricCardVal}
              style={{
                color: score >= 75 ? "var(--green)" : score >= 50 ? "var(--amber)" : "var(--red)",
              }}
            >
              {score}
            </span>
          </div>
          <span className={styles.metricCardLbl}>Health Score</span>
        </div>
      </div>

      <div className={styles.twoColumn}>
        {/* Left — Standup cards */}
        <div className={styles.mainCol}>
          {isLoading ? (
            <div className={styles.skeletonCard}>
              <div className={styles.skeletonLine} style={{ width: "40%" }} />
              <div className={styles.skeletonLine} style={{ width: "80%" }} />
              <div className={styles.skeletonLine} style={{ width: "60%" }} />
            </div>
          ) : Object.keys(filteredGrouped).length === 0 ? (
            <div className={styles.emptyCard}>
              <RiSparklingLine size={32} color="var(--text-3)" />
              <p>
                {search.trim()
                  ? "No standups match your search."
                  : `No standups for this date${selectedPod ? ` · ${selectedPod}` : ""}.`}
              </p>
            </div>
          ) : (
            Object.entries(filteredGrouped).map(([pod, standups]) => (
              <div key={pod} className={styles.podGroup}>
                <div className={styles.podHeader}>
                  <span>{pod}</span>
                  <span className={styles.podBadge}>{standups.length}</span>
                </div>
                <div className={styles.cardGrid}>
                  {standups.map((s) => (
                    <button
                      key={s.id}
                      className={styles.gridCard}
                      onClick={() => setDetailStandup(s)}
                    >
                      <div className={styles.gridCardTop}>
                        <div className={styles.gridCardAvatar} style={{ background: getAvatarColor(s.engineer) }}>
                          {initials(s.engineer)}
                        </div>
                        <div className={styles.gridCardMeta}>
                          <span className={styles.gridCardName}>{s.engineer}</span>
                          <span className={styles.gridCardPod}>{s.pod}</span>
                        </div>
                        <div className={styles.gridCardBadges}>
                          <span className={styles.streakBadge} title={`${getStreak(s.engineer)}-day streak`}>
                            <RiFireLine size={9} /> {getStreak(s.engineer)}
                          </span>
                          <span className={styles.wordBadge} title="Word count">
                            {wordCount(s)}w
                          </span>
                          {s.blockers?.trim() ? (
                            <span className={styles.gridCardBlockerBadge}>
                              <RiAlertLine size={10} />
                            </span>
                          ) : wordCount(s) >= 60 ? (
                            <span className={styles.flyingBadge} title="Flying — detailed standup">🚀</span>
                          ) : null}
                        </div>
                      </div>
                      <div className={styles.gridCardSections}>
                        <div className={styles.gridCardSection}>
                          <span className={styles.gridCardSectionLbl}>Yesterday</span>
                          <p className={styles.gridCardSectionText}>
                            {s.yesterday.slice(0, 90)}{s.yesterday.length > 90 ? "…" : ""}
                          </p>
                        </div>
                        <div className={styles.gridCardSection}>
                          <span className={styles.gridCardSectionLbl}>Today</span>
                          <p className={styles.gridCardSectionText}>
                            {s.today.slice(0, 90)}{s.today.length > 90 ? "…" : ""}
                          </p>
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            ))
          )}
        </div>

        {/* Right — EOS Intelligence */}
        <div className={styles.sideCol}>
          <div className={styles.intelligenceCard}>
            <div className={styles.intelligenceHeader}>
              <RiSparklingLine size={14} color="var(--accent)" />
              <span>EOS Intelligence</span>
            </div>

            <div className={styles.intelligenceBody}>
              {/* Synthesize */}
              <button
                className={styles.synthesizeBtn}
                onClick={synthesizeStandups}
                disabled={synthesizing || teamStandups.length === 0}
              >
                {synthesizing ? (
                  <><span className={styles.synSpinner} /> Synthesizing…</>
                ) : (
                  <><RiSparklingLine size={12} /> Synthesize team standup</>
                )}
              </button>

              {synthesis && (
                <div className={styles.synthesisCard}>
                  <div className={styles.synthesisLabel}>
                    <RiSparklingLine size={10} /> Team Summary
                  </div>
                  <p className={styles.synthesisText}>{synthesis}</p>
                </div>
              )}

              {/* Blockers */}
              {blockers.length > 0 && (
                <div className={styles.intelSection}>
                  <div className={styles.intelSectionTitle}>
                    <RiAlertLine size={12} color="var(--red)" /> Active Blockers
                  </div>
                  <div className={styles.blockerList}>
                    {blockers.map((s) => (
                      <div key={s.id} className={styles.blockerItem}>
                        <div className={styles.blockerItemHeader}>
                          <span className={styles.blockerItemName}>{s.engineer}</span>
                          <span className={styles.blockerItemPod}>{s.pod}</span>
                        </div>
                        <p className={styles.blockerItemText}>{s.blockers}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Missing */}
              {missingMembers.length > 0 && (
                <div className={styles.intelSection}>
                  <div className={styles.intelSectionTitle}>
                    <RiTimeLine size={12} color="var(--amber)" /> Not Submitted
                  </div>
                  <div className={styles.missingGrid}>
                    {missingMembers.map((m) => (
                      <span key={m} className={styles.missingTag}>{m}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Themes */}
              {themes.length > 0 && (
                <div className={styles.intelSection}>
                  <div className={styles.intelSectionTitle}>
                    <RiBarChartBoxLine size={12} color="var(--accent)" /> Today&apos;s Themes
                  </div>
                  <div className={styles.themeGrid}>
                    {themes.map((t) => (
                      <span key={t.word} className={styles.themeTag}>
                        {t.word} <strong>×{t.count}</strong>
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {blockers.length === 0 && missingMembers.length === 0 && !synthesis && (
                <div className={styles.allClear}>
                  <RiCheckboxCircleLine size={24} color="var(--green)" />
                  <p>All clear — full team submitted, no blockers.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <StandupDetailDrawer
        standup={detailStandup}
        open={!!detailStandup}
        onClose={() => setDetailStandup(null)}
      />
    </div>
  );
}
