import type { TicketsResponse, SummaryResponse, FiltersResponse, Sprint, OrgMember } from '@/types'

export const DUMMY_FILTERS: FiltersResponse = {
  users: [
    'Admin','Anoop Rai','Aastha Rai','Anand Verma','Rahul Sharma','ishu rana',
    'Vishnuvardhan Goud','Piyush Soni','Prakash Kumar',
    'Niral','Shivam','Deepak Kumar','Akash Kumar',
  ],
  clients: ['Colgate','Jockey','SAAS','BSV','ReckittBenckiser','Henkel','Unilever'],
  pods:    ['DPAI','SNOP','EDM','PLAT','SNOE','PA'],
  projects:['DPAI','SNOP','EDM','PLAT','SNOE','PA'],
}

export const DUMMY_ORG_MEMBERS: OrgMember[] = [
  { id: 'u1', name: 'Admin', email: 'admin@3scsolution.com', role: 'admin', pod: 'DPAI', emp_no: 'E001', reporting_to: null, title: 'Platform Admin' },
  { id: 'u2', name: 'Anoop Rai', email: 'anoop.rai@3scsolution.com', role: 'engineering_manager', pod: 'DPAI', emp_no: 'E002', reporting_to: 'E001', title: 'Engineering Manager' },
  { id: 'u3', name: 'Anand Verma', email: 'anand.verma@3scsolution.com', role: 'tech_lead', pod: 'DPAI', emp_no: 'E003', reporting_to: 'E002', title: 'Tech Lead — DPAI' },
  { id: 'u4', name: 'Vishnuvardhan Goud', email: 'vishnu.goud@3scsolution.com', role: 'tech_lead', pod: 'EDM', emp_no: 'E004', reporting_to: 'E002', title: 'Tech Lead — EDM' },
  { id: 'u5', name: 'Aastha Rai', email: 'aastha.rai@3scsolution.com', role: 'team_member', pod: 'DPAI', emp_no: 'E005', reporting_to: 'E003', title: 'Frontend Engineer' },
  { id: 'u6', name: 'Rahul Sharma', email: 'rahul.sharma@3scsolution.com', role: 'team_member', pod: 'DPAI', emp_no: 'E006', reporting_to: 'E003', title: 'Backend Engineer' },
  { id: 'u7', name: 'ishu rana', email: 'ishu.rana@3scsolution.com', role: 'team_member', pod: 'DPAI', emp_no: 'E007', reporting_to: 'E003', title: 'ML Engineer' },
  { id: 'u8', name: 'Shivam', email: 'shivam@3scsolution.com', role: 'team_member', pod: 'DPAI', emp_no: 'E008', reporting_to: 'E003', title: 'DevOps Engineer' },
  { id: 'u9', name: 'Akash Kumar', email: 'akash.kumar@3scsolution.com', role: 'team_member', pod: 'DPAI', emp_no: 'E009', reporting_to: 'E003', title: 'QA Engineer' },
  { id: 'u10', name: 'Piyush Soni', email: 'piyush.soni@3scsolution.com', role: 'team_member', pod: 'EDM', emp_no: 'E010', reporting_to: 'E004', title: 'Data Engineer' },
  { id: 'u11', name: 'Prakash Kumar', email: 'prakash.kumar@3scsolution.com', role: 'team_member', pod: 'EDM', emp_no: 'E011', reporting_to: 'E004', title: 'Backend Engineer' },
  { id: 'u12', name: 'Niral', email: 'niral@3scsolution.com', role: 'team_member', pod: 'EDM', emp_no: 'E012', reporting_to: 'E004', title: 'Full Stack Engineer' },
  { id: 'u13', name: 'Deepak Kumar', email: 'deepak.kumar@3scsolution.com', role: 'team_member', pod: 'EDM', emp_no: 'E013', reporting_to: 'E004', title: 'Data Analyst' },
]

export const DUMMY_SUMMARY: SummaryResponse = {
  total_hours:   8420,
  total_tickets: 1847,
  by_issue_type: [
    { issue_type: 'Feature', tickets: 920, hours: 4200, pct: 49.8 },
    { issue_type: 'Bug', tickets: 580, hours: 2100, pct: 31.4 },
    { issue_type: 'Task', tickets: 240, hours: 1300, pct: 13.0 },
    { issue_type: 'Meeting', tickets: 107, hours: 820, pct: 5.8 },
  ],
  by_pod: [
    { pod: 'DPAI',       hours: 2108, tickets: 412, clients: ['Colgate','Jockey'] },
    { pod: 'SNOP',       hours: 1580, tickets: 298, clients: ['SAAS','Colgate']  },
    { pod: 'EDM',        hours: 1302, tickets: 241, clients: ['SAAS','BSV']      },
    { pod: 'PLAT',       hours: 1024, tickets: 198, clients: ['BSV','Jockey']    },
    { pod: 'SNOE',       hours:  791, tickets: 142, clients: ['SAAS']            },
    { pod: 'PA',         hours:  604, tickets: 118, clients: ['Colgate']         },
  ],
  by_client: [
    { client: 'Colgate',          hours: 1480, tickets: 312, users: ['Anand Verma','Rahul Sharma'] },
    { client: 'Jockey',           hours: 1080, tickets: 241, users: ['Aastha Rai','Niral']        },
    { client: 'SAAS',             hours:  864, tickets: 198, users: ['ishu rana','Shivam']         },
    { client: 'BSV',              hours:  612, tickets: 142, users: ['Niral','Piyush Soni']        },
    { client: 'ReckittBenckiser', hours:  540, tickets:  98, users: ['Deepak Kumar']               },
    { client: 'Henkel',           hours:  420, tickets:  87, users: ['Akash Kumar']                },
    { client: 'Unilever',         hours:  380, tickets:  71, users: ['Vishnuvardhan Goud']         },
  ],
  by_user: [
    { user: 'Anand Verma',       hours: 48, tickets: 12, clients: ['Colgate','SAAS']   },
    { user: 'Vishnuvardhan Goud',hours: 42, tickets:  9, clients: ['SAAS','Colgate']   },
    { user: 'Piyush Soni',       hours: 38, tickets:  7, clients: ['SAAS','BSV']       },
    { user: 'Aastha Rai',        hours: 31, tickets: 14, clients: ['Jockey']           },
    { user: 'ishu rana',         hours: 28, tickets: 18, clients: ['SAAS']             },
    { user: 'Rahul Sharma',      hours: 24, tickets:  8, clients: ['Colgate']          },
    { user: 'Niral',             hours: 22, tickets:  5, clients: ['BSV','Jockey']     },
    { user: 'Shivam',            hours: 19, tickets:  4, clients: ['SAAS']             },
    { user: 'Prakash Kumar',     hours: 17, tickets:  6, clients: ['SAAS','BSV']       },
    { user: 'Deepak Kumar',      hours: 15, tickets:  5, clients: ['ReckittBenckiser'] },
    { user: 'Akash Kumar',       hours: 14, tickets:  4, clients: ['Henkel']           },
    { user: 'Anoop Rai',         hours: 12, tickets:  3, clients: ['DPAI']             },
    { user: 'Admin',             hours:  8, tickets:  2, clients: ['Internal']         },
  ],
}

export const DUMMY_TICKETS: TicketsResponse = {
  count: 1847,
  total: 1847,
  limit: 20,
  offset: 0,
  tickets: [
    { key:'DPAI-6998', project_key:'DPAI', project_name:'DPAI', summary:'ML pipeline for Colgate analytics dashboard', assignee:'Anand Verma', assignee_email:'anand@3sc.com', status:'Done', client:'Colgate', pod:'DPAI', hours_spent:12, original_estimate_hours:16, remaining_estimate_hours:4, created:'2026-03-01', updated:'2026-03-08', issue_type:'Feature', priority:'High', url:'#', worklogs:[] },
    { key:'DPAI-7013', project_key:'DPAI', project_name:'DPAI', summary:'Drag & Drop column resize not working in data grid', assignee:'Aastha Rai', assignee_email:'aastha@3sc.com', status:'Open', client:'Jockey', pod:'DPAI', hours_spent:0, original_estimate_hours:4, remaining_estimate_hours:4, created:'2026-03-12', updated:'2026-03-12', issue_type:'Bug', priority:'High', url:'#', worklogs:[] },
    { key:'DPAI-7007', project_key:'DPAI', project_name:'DPAI', summary:'Failed error text showing in English in Forecasting module', assignee:'ishu rana', assignee_email:'ishu@3sc.com', status:'Done', client:'SAAS', pod:'DPAI', hours_spent:3, original_estimate_hours:4, remaining_estimate_hours:1, created:'2026-03-05', updated:'2026-03-07', issue_type:'Bug', priority:'Medium', url:'#', worklogs:[] },
    { key:'DPAI-6985', project_key:'DPAI', project_name:'DPAI', summary:'AKS Cluster migration to private network', assignee:'Vishnuvardhan Goud', assignee_email:'vishnu@3sc.com', status:'Done', client:'SAAS', pod:'DevOps', hours_spent:10, original_estimate_hours:12, remaining_estimate_hours:2, created:'2026-03-01', updated:'2026-03-15', issue_type:'Feature', priority:'High', url:'#', worklogs:[] },
    { key:'DPAI-6972', project_key:'DPAI', project_name:'DPAI', summary:'EDM data schema migration v8', assignee:'Piyush Soni', assignee_email:'piyush@3sc.com', status:'In Progress', client:'SAAS', pod:'EDM', hours_spent:14, original_estimate_hours:16, remaining_estimate_hours:2, created:'2026-03-01', updated:'2026-03-20', issue_type:'Feature', priority:'High', url:'#', worklogs:[] },
    { key:'DPAI-6960', project_key:'DPAI', project_name:'DPAI', summary:'VAPT scan for DPAI module Q1 security audit', assignee:'Shivam', assignee_email:'shivam@3sc.com', status:'Done', client:'SAAS', pod:'Infosec', hours_spent:7.5, original_estimate_hours:8, remaining_estimate_hours:0.5, created:'2026-03-10', updated:'2026-03-22', issue_type:'Feature', priority:'High', url:'#', worklogs:[] },
    { key:'DPAI-6944', project_key:'DPAI', project_name:'DPAI', summary:'SNP RP v10 Development BSV client integration', assignee:'Niral', assignee_email:'niral@3sc.com', status:'In Progress', client:'BSV', pod:'SNP', hours_spent:9, original_estimate_hours:10, remaining_estimate_hours:1, created:'2026-03-01', updated:'2026-03-25', issue_type:'Feature', priority:'Medium', url:'#', worklogs:[] },
    { key:'DPAI-6930', project_key:'DPAI', project_name:'DPAI', summary:'Daily standup Sprint 42', assignee:'Anand Verma', assignee_email:'anand@3sc.com', status:'Done', client:'SAAS', pod:'DPAI', hours_spent:2.5, original_estimate_hours:0, remaining_estimate_hours:0, created:'2026-03-01', updated:'2026-03-31', issue_type:'Meeting', priority:'Low', url:'#', worklogs:[] },
  ],
}

export const DUMMY_SPRINTS: Sprint[] = [
  {
    id: 'sprint-42',
    name: 'Sprint 42 — Colgate Integration',
    goal: 'Complete Colgate analytics integration and BSV client rollout',
    start_date: '2026-03-01',
    end_date: '2026-04-30',
    status: 'active',
    total_points: 45,
    done_points: 28,
    ticket_count: 6,
    completion_pct: 62,
    velocity: 22,
    tickets: DUMMY_TICKETS.tickets.slice(0, 6),
    pod: 'DPAI',
  },
  {
    id: 'sprint-41',
    name: 'Sprint 41 — Security & DevOps',
    goal: 'VAPT scans and AKS migration',
    start_date: '2026-02-01',
    end_date: '2026-02-28',
    status: 'completed',
    total_points: 38,
    done_points: 38,
    ticket_count: 4,
    completion_pct: 100,
    velocity: 19,
    pod: 'PLAT',
  },
  {
    id: 'sprint-43',
    name: 'Sprint 43 — Forecasting Enhancements',
    goal: 'Improve forecasting module and reporting dashboards',
    start_date: '2026-05-01',
    end_date: '2026-05-31',
    status: 'planning',
    total_points: 50,
    done_points: 0,
    ticket_count: 0,
    completion_pct: 0,
    velocity: null,
    pod: 'DPAI',
  },
  {
    id: 'sprint-snop-44',
    name: 'Sprint 44 — Demand Planning',
    goal: 'Deliver demand planning module enhancements',
    start_date: '2026-04-01',
    end_date: '2026-04-14',
    status: 'active',
    total_points: 40,
    done_points: 25,
    ticket_count: 5,
    completion_pct: 62,
    velocity: 20,
    pod: 'SNOP',
  },
  {
    id: 'sprint-edm-45',
    name: 'Sprint 45 — Schema Migration',
    goal: 'Complete EDM schema migration and data quality checks',
    start_date: '2026-04-01',
    end_date: '2026-04-14',
    status: 'active',
    total_points: 35,
    done_points: 18,
    ticket_count: 4,
    completion_pct: 51,
    velocity: 17,
    pod: 'EDM',
  },
  {
    id: 'sprint-snoe-46',
    name: 'Sprint 46 — Territory Planning',
    goal: 'Territory planning module and sales analytics v2',
    start_date: '2026-04-07',
    end_date: '2026-04-21',
    status: 'active',
    total_points: 20,
    done_points: 10,
    ticket_count: 3,
    completion_pct: 50,
    velocity: 12,
    pod: 'SNOE',
  },
  {
    id: 'sprint-pa-47',
    name: 'Sprint 47 — Recommendation Engine',
    goal: 'Recommendation engine POC and AI feature flags',
    start_date: '2026-04-01',
    end_date: '2026-04-14',
    status: 'active',
    total_points: 25,
    done_points: 12,
    ticket_count: 3,
    completion_pct: 48,
    velocity: 14,
    pod: 'PA',
  },
]
