import { useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { fetchWorkload, fetchKnowledgeGaps, detectKnowledgeGaps, createWikiPage, fetchWikiSpaces, fetchVelocity, analyzeTicketNL } from "@/services/api";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
} from "recharts";
import { RiSparklingLine, RiAlertLine, RiFileTextLine, RiHeartPulseLine, RiUserLine, RiGlobalLine, RiTeamLine, RiBarChartLine, RiArrowUpLine, RiArrowDownLine } from "react-icons/ri";
import type { KnowledgeGap } from "@/types";
import styles from "./AnalyticsPage.module.css";

export default function AnalyticsPage() {
  const qc = useQueryClient();

  const { data: workload = [] } = useQuery({
    queryKey: ["analytics-workload"],
    queryFn: fetchWorkload,
  });

  const { data: gaps = [], isLoading: loadingGaps } = useQuery({
    queryKey: ["knowledge-gaps"],
    queryFn: fetchKnowledgeGaps,
  });

  const { data: spaces = [] } = useQuery({
    queryKey: ["wiki-spaces"],
    queryFn: fetchWikiSpaces,
  });

  const { data: velocityData = [] } = useQuery({
    queryKey: ["velocity"],
    queryFn: fetchVelocity,
  });

  const detectMut = useMutation({
    mutationFn: detectKnowledgeGaps,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["knowledge-gaps"] });
      toast.success("Knowledge gap detection started!");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const createStubMut = useMutation({
    mutationFn: ({ gap }: { gap: KnowledgeGap }) => {
      const spaceId = spaces[0]?.id;
      if (!spaceId) throw new Error("No wiki spaces found");
      return createWikiPage({
        space_id: spaceId,
        title:    `[Stub] ${gap.topic}`,
        content:  `# ${gap.topic}\n\n> This page was auto-created from a knowledge gap detection.\n\n## Description\n\n${gap.description}\n\n## TODO\n\n- [ ] Add relevant documentation\n- [ ] Link to related tickets\n`,
      });
    },
    onSuccess: () => {
      toast.success("Wiki stub created!");
      qc.invalidateQueries({ queryKey: ["wiki-pages"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const generateArticleMut = useMutation({
    mutationFn: async ({ gap }: { gap: KnowledgeGap }) => {
      const spaceId = spaces[0]?.id;
      if (!spaceId) throw new Error("No wiki spaces found");
      const analysis = await analyzeTicketNL(
        `Write a comprehensive technical wiki article about "${gap.topic}". ` +
        `Context: ${gap.description}. ` +
        `Include sections: Overview, When This Comes Up, Common Patterns, Best Practices, Troubleshooting. ` +
        `Based on ${gap.ticket_count} unresolved tickets that needed this knowledge.`
      );
      const body = analysis.description ??
        `## Overview\n\n${gap.description}\n\n## Common Patterns\n\nTODO\n\n## Best Practices\n\nTODO\n\n## Troubleshooting\n\nTODO`;
      return createWikiPage({
        space_id: spaceId,
        title: gap.topic,
        content: `# ${gap.topic}\n\n> ✦ Generated by EOS · Based on ${gap.ticket_count} tickets · ${new Date().toLocaleDateString()}\n\n${body}`,
      });
    },
    onSuccess: () => {
      toast.success("EOS generated the wiki article!");
      qc.invalidateQueries({ queryKey: ["wiki-pages"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const sortedWorkload = [...workload].sort((a, b) => b.total_hours - a.total_hours).slice(0, 20);

  // Team Health Monitor
  const teamHealth = useMemo(() => {
    if (workload.length === 0) return [];
    const avg = workload.reduce((s, w) => s + w.total_hours, 0) / workload.length;
    return workload.map((w) => {
      const ratio = w.total_hours / Math.max(1, avg);
      const burnoutRisk = w.total_hours > 50 ? "High" : w.total_hours > 40 ? "Medium" : "Low";
      const overloaded = ratio > 1.4;
      return { ...w, avg, ratio, burnoutRisk, overloaded };
    }).sort((a, b) => b.total_hours - a.total_hours);
  }, [workload]);

  // Velocity anomaly detection
  const velocityAnomalies = useMemo(() => {
    if (velocityData.length < 2) return [];
    const anomalies: { sprint: string; prevSprint: string; dropPct: number; committed: number; completed: number }[] = [];
    for (let i = 1; i < velocityData.length; i++) {
      const prev = velocityData[i - 1];
      const curr = velocityData[i];
      if (prev.completed > 0) {
        const change = (curr.completed - prev.completed) / prev.completed;
        if (change <= -0.2) {
          anomalies.push({ sprint: curr.sprint, prevSprint: prev.sprint, dropPct: Math.abs(change), committed: curr.committed, completed: curr.completed });
        }
      }
    }
    return anomalies;
  }, [velocityData]);

  // Emotion-Aware: mock sentiment signals
  const sentimentSignals = [
    { engineer: "Priya S.", signal: "Frustration", phrases: ["'this keeps breaking'", "'same issue again'"], sprint: "Sprint 9", severity: "high" as const },
    { engineer: "Rahul D.", signal: "Overload", phrases: ["'too many things at once'", "'not enough time'"], sprint: "Sprint 9", severity: "high" as const },
    { engineer: "Karan M.", signal: "Disengagement", phrases: ["'not sure why we're doing this'"], sprint: "Sprint 9", severity: "medium" as const },
  ];

  // Cross-Org Benchmarks: static industry data
  const benchmarks = [
    { metric: "Sprint predictability", yourValue: "61%", industryAvg: "68%", similar: "79%", direction: "up" as const, insight: "Teams with your velocity profile who adopted sprint scope freeze policies improved predictability by 34%." },
    { metric: "Avg ticket resolution time", yourValue: "3.4d", industryAvg: "4.1d", similar: "2.8d", direction: "down" as const, insight: "Your resolution time is 17% better than industry average. Similar-stage teams with dedicated triage rotations reach 2.8d." },
    { metric: "Knowledge coverage", yourValue: "54%", industryAvg: "48%", similar: "71%", direction: "up" as const, insight: "Teams with weekly doc-review rituals reach 71% wiki coverage within 6 months." },
  ];

  // Predictive Resource Planning: mock roadmap → gap data
  const resourceGaps = [
    { goal: "Q3: ML-powered ticket routing", skill: "Senior ML Engineer", urgency: "high" as const, neededBy: "June 2029", note: "No ML expertise on current team. Lead time ~3 months. Start hiring now." },
    { goal: "Q3: Infrastructure auto-scaling", skill: "DevOps / SRE Specialist", urgency: "high" as const, neededBy: "August 2029", note: "Current team has 1 DevOps generalist. Dedicated SRE needed for 99.9% SLA target." },
    { goal: "Q4: Mobile SDK", skill: "iOS Engineer", urgency: "medium" as const, neededBy: "October 2029", note: "No mobile engineers. Consider contracting for initial SDK, then hire full-time in Q4." },
  ];

  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <h1 className={styles.title}>Analytics</h1>
        <p className={styles.subtitle}>Workload distribution and knowledge insights</p>
      </div>

      {/* Workload Chart */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div className={styles.cardTitle}>Workload Distribution</div>
          <span className={styles.cardSub}>Hours by engineer (top 20)</span>
        </div>
        {sortedWorkload.length === 0 ? (
          <p className={styles.empty}>No workload data available.</p>
        ) : (
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={sortedWorkload} layout="vertical" margin={{ left: 100, right: 20, top: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 11, fill: "var(--text-2)" }} />
              <YAxis
                type="category"
                dataKey="engineer"
                tick={{ fontSize: 11, fill: "var(--text-2)" }}
                width={100}
              />
              <Tooltip
                contentStyle={{ background: "var(--surface-2)", border: "1px solid var(--border-2)", borderRadius: 8 }}
                formatter={(v: number) => [`${v.toFixed(1)}h`, "Hours"]}
              />
              <Bar dataKey="total_hours" fill="var(--accent)" radius={[0,4,4,0]} />
            </BarChart>
          </ResponsiveContainer>
        )}
      </div>

      {/* ── Team Health Monitor ── */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Team Health Monitor</div>
            <span className={styles.cardSub}>Workload balance · Burnout risk detection</span>
          </div>
          <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
        </div>
        {teamHealth.length === 0 ? (
          <p className={styles.empty}>No workload data available.</p>
        ) : (
          <div className={styles.healthList}>
            {teamHealth.slice(0, 8).map((m) => (
              <div key={m.engineer} className={`${styles.healthRow} ${m.overloaded ? styles.healthRowAlert : ""}`}>
                <div className={styles.healthAvatar}>
                  <RiUserLine size={13} />
                </div>
                <div className={styles.healthInfo}>
                  <span className={styles.healthName}>{m.engineer}</span>
                  <div className={styles.healthBar}>
                    <div
                      className={styles.healthBarFill}
                      style={{
                        width: `${Math.min(100, (m.total_hours / 60) * 100)}%`,
                        background: m.burnoutRisk === "High" ? "var(--red)" : m.burnoutRisk === "Medium" ? "var(--amber)" : "var(--green)",
                      }}
                    />
                  </div>
                </div>
                <span className={styles.healthHrs}>{m.total_hours.toFixed(0)}h</span>
                <span className={`${styles.healthBadge} ${
                  m.burnoutRisk === "High" ? styles.healthBadgeHigh
                  : m.burnoutRisk === "Medium" ? styles.healthBadgeMed
                  : styles.healthBadgeLow
                }`}>
                  {m.burnoutRisk === "High" ? <><RiAlertLine size={9} /> High Risk</>
                   : m.burnoutRisk === "Medium" ? <><RiHeartPulseLine size={9} /> Watch</>
                   : "Healthy"}
                </span>
              </div>
            ))}
            {teamHealth.filter((m) => m.burnoutRisk === "High").length > 0 && (
              <div className={styles.healthRec}>
                <RiSparklingLine size={11} color="var(--accent)" />
                <span>EOS detected {teamHealth.filter((m) => m.burnoutRisk === "High").length} team member(s) at high burnout risk. Consider redistributing tasks or reducing sprint scope.</span>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ── Velocity Anomaly Detection ── */}
      <div className={`${styles.card} ${velocityAnomalies.length > 0 ? styles.cardAlert : ""}`}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Velocity Anomaly Detection</div>
            <span className={styles.cardSub}>Sprint-over-sprint pattern analysis</span>
          </div>
          <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
        </div>

        {velocityData.length < 2 ? (
          <p className={styles.empty}>Need at least 2 completed sprints for anomaly analysis.</p>
        ) : velocityAnomalies.length === 0 ? (
          <div className={styles.anomalyHealthy}>
            <RiSparklingLine size={16} color="var(--green)" />
            <span>No velocity anomalies detected. Sprint-over-sprint performance looks consistent.</span>
          </div>
        ) : (
          <div className={styles.anomalyList}>
            {velocityAnomalies.map((a, i) => (
              <div key={i} className={styles.anomalyItem}>
                <div className={styles.anomalyTop}>
                  <RiAlertLine size={13} color="var(--amber)" />
                  <span className={styles.anomalyTitle}>
                    {a.sprint} velocity dropped <strong>{Math.round(a.dropPct * 100)}%</strong> from {a.prevSprint}
                  </span>
                  <span className={styles.anomalyBadge}>Anomaly</span>
                </div>
                <div className={styles.anomalyMeta}>
                  <span>Committed: <strong>{a.committed} pts</strong></span>
                  <span>Completed: <strong style={{ color: "var(--amber)" }}>{a.completed} pts</strong></span>
                  <span>Shortfall: <strong style={{ color: "var(--red)" }}>{a.committed - a.completed} pts</strong></span>
                </div>
                <p className={styles.anomalyRec}>
                  ✦ EOS recommends reviewing mid-sprint scope changes and team capacity for {a.sprint}. Consider a sprint scope freeze policy.
                </p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ── Emotion-Aware Work Management ── */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Emotion-Aware Work Management</div>
            <span className={styles.cardSub}>Linguistic signals in comments and ticket updates · Last 72 hours</span>
          </div>
          <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
        </div>
        <div className={styles.sentimentList}>
          {sentimentSignals.map((s) => (
            <div key={s.engineer} className={`${styles.sentimentRow} ${s.severity === "high" ? styles.sentimentRowHigh : styles.sentimentRowMed}`}>
              <div className={styles.sentimentAvatar}><RiUserLine size={13} /></div>
              <div className={styles.sentimentInfo}>
                <div className={styles.sentimentName}>{s.engineer}</div>
                <div className={styles.sentimentPhrases}>
                  {s.phrases.map((p) => <span key={p} className={styles.sentimentPhrase}>{p}</span>)}
                </div>
              </div>
              <div className={styles.sentimentMeta}>
                <span className={`${styles.sentimentBadge} ${s.severity === "high" ? styles.sentimentBadgeHigh : styles.sentimentBadgeMed}`}>{s.signal}</span>
                <span className={styles.sentimentSprint}>{s.sprint}</span>
              </div>
            </div>
          ))}
          <div className={styles.sentimentRec}>
            <RiSparklingLine size={11} color="var(--accent)" />
            <span>EOS detected emotional friction signals in Sprint 9 — not surveillance, care. Consider a team check-in before sprint end.</span>
          </div>
        </div>
      </div>

      {/* ── Cross-Organizational Pattern Learning ── */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Cross-Organizational Pattern Learning</div>
            <span className={styles.cardSub}>Anonymized benchmarks · opt-in · similar-stage engineering teams</span>
          </div>
          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <span className={styles.privacyBadge}><RiGlobalLine size={9} /> Anonymized</span>
            <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
          </div>
        </div>
        <div className={styles.benchmarkList}>
          {benchmarks.map((b) => (
            <div key={b.metric} className={styles.benchmarkItem}>
              <div className={styles.benchmarkHeader}>
                <span className={styles.benchmarkMetric}>{b.metric}</span>
                <div className={styles.benchmarkValues}>
                  <span className={styles.benchmarkYours}>You: <strong>{b.yourValue}</strong></span>
                  <span className={styles.benchmarkIndustry}>Industry avg: {b.industryAvg}</span>
                  <span className={`${styles.benchmarkSimilar} ${b.direction === "up" ? styles.benchmarkUp : styles.benchmarkDown}`}>
                    {b.direction === "up" ? <RiArrowUpLine size={10} /> : <RiArrowDownLine size={10} />}
                    Similar teams: {b.similar}
                  </span>
                </div>
              </div>
              <p className={styles.benchmarkInsight}>{b.insight}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Predictive Resource Planning ── */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Predictive Resource Planning</div>
            <span className={styles.cardSub}>Based on Q3–Q4 roadmap goals · Current team skill profile</span>
          </div>
          <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
        </div>
        <div className={styles.resourceList}>
          {resourceGaps.map((r) => (
            <div key={r.goal} className={`${styles.resourceItem} ${r.urgency === "high" ? styles.resourceItemHigh : styles.resourceItemMed}`}>
              <div className={styles.resourceHeader}>
                <span className={`${styles.resourceUrgency} ${r.urgency === "high" ? styles.resourceUrgencyHigh : styles.resourceUrgencyMed}`}>
                  {r.urgency === "high" ? "Hire Now" : "Plan Q4"}
                </span>
                <span className={styles.resourceNeededBy}>Needed by {r.neededBy}</span>
              </div>
              <div className={styles.resourceSkill}>{r.skill}</div>
              <div className={styles.resourceGoal}><RiBarChartLine size={10} /> For: {r.goal}</div>
              <p className={styles.resourceNote}>{r.note}</p>
            </div>
          ))}
          <div className={styles.resourceRec}>
            <RiTeamLine size={11} color="var(--accent)" />
            <span>EOS forecasts a 3-person gap by Q3 based on current roadmap velocity. Recommended: start ML Engineer search immediately (3-month lead time).</span>
          </div>
        </div>
      </div>

      {/* Knowledge Gaps */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div>
            <div className={styles.cardTitle}>Knowledge Gaps</div>
            <span className={styles.cardSub}>Topics with tickets but no wiki docs</span>
          </div>
          <div className={styles.gapActions}>
            <div className={styles.novaBadge}>
              <span className={styles.novaGlow} />
              EOS-powered
            </div>
            <button
              className="btn btn-ghost btn-sm"
              onClick={() => detectMut.mutate()}
              disabled={detectMut.isPending}
            >
              {detectMut.isPending ? "Detecting…" : "Run Detection"}
            </button>
          </div>
        </div>

        {loadingGaps ? (
          <p className={styles.empty}>Loading gaps…</p>
        ) : gaps.length === 0 ? (
          <div className={styles.emptyState}>
            <span className={styles.emptyIcon}>✅</span>
            <p>No knowledge gaps detected. All topics have wiki coverage!</p>
          </div>
        ) : (
          <div className={styles.gapList}>
            {gaps.map((gap) => (
              <div key={gap.id} className={styles.gapItem}>
                <div className={styles.gapInfo}>
                  <div className={styles.gapTopic}>{gap.topic}</div>
                  <div className={styles.gapDesc}>{gap.description}</div>
                  <div className={styles.gapMeta}>
                    <span>{gap.ticket_count} tickets</span>
                    <span>·</span>
                    <span>{gap.wiki_count} wiki pages</span>
                    <span>·</span>
                    <span>{new Date(gap.detected_at).toLocaleDateString()}</span>
                  </div>
                </div>
                <div className={styles.gapBtns}>
                  <button
                    className={styles.generateBtn}
                    onClick={() => generateArticleMut.mutate({ gap })}
                    disabled={generateArticleMut.isPending}
                    title="EOS writes a full wiki article from ticket patterns"
                  >
                    {generateArticleMut.isPending ? (
                      <><span className={styles.btnSpinner} /> Writing…</>
                    ) : (
                      <><RiSparklingLine size={11} /> Generate Article</>
                    )}
                  </button>
                  <button
                    className={styles.createStubBtn}
                    onClick={() => createStubMut.mutate({ gap })}
                    disabled={createStubMut.isPending}
                  >
                    <RiFileTextLine size={11} /> Stub
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
