import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import {
  fetchTeamStandups, fetchTodayStandup, updateStandup, generateStandup, novaQuery,
} from "@/services/api";
import { fetchFilters } from "@/services/api";
import { QUERY_KEYS } from "@/config/queryKeys";
import { useAuthStore } from "@/features/auth/useAuthStore";
import type { Standup } from "@/types";
import { RiSparklingLine, RiCheckboxCircleLine, RiTimeLine, RiAlertLine } from "react-icons/ri";
import styles from "./StandupPage.module.css";

export default function StandupPage() {
  const { user } = useAuthStore();
  const qc = useQueryClient();
  const [selectedPod, setSelectedPod]   = useState("");
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().slice(0, 10));
  const [editing, setEditing]           = useState<Standup | null>(null);
  const [editForm, setEditForm]         = useState({ yesterday: "", today: "", blockers: "" });

  const isManager = user?.role === "engineering_manager" || user?.role === "admin";

  const { data: filtersData } = useQuery({ queryKey: QUERY_KEYS.filters(), queryFn: fetchFilters });

  const { data: teamStandups = [], isLoading } = useQuery({
    queryKey: ["team-standups", selectedDate, selectedPod],
    queryFn: () => fetchTeamStandups(selectedDate, selectedPod || undefined),
  });

  const { data: myStandup, isLoading: loadingMine } = useQuery({
    queryKey: ["my-standup"],
    queryFn: fetchTodayStandup,
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      toast.success("Standup generated by EOS!");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: number; payload: Partial<Standup> }) =>
      updateStandup(id, payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(null);
      toast.success("Standup updated");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  function startEdit(s: Standup) {
    setEditing(s);
    setEditForm({ yesterday: s.yesterday, today: s.today, blockers: s.blockers });
  }

  function saveEdit() {
    if (!editing) return;
    updateMut.mutate({ id: editing.id, payload: editForm });
  }

  // Group by POD for manager view
  const grouped = teamStandups.reduce<Record<string, Standup[]>>((acc, s) => {
    const pod = s.pod || "—";
    if (!acc[pod]) acc[pod] = [];
    acc[pod].push(s);
    return acc;
  }, {});

  // Autonomous standup synthesis
  const [synthesizing, setSynthesizing] = useState(false);
  const [synthesis, setSynthesis] = useState<string | null>(null);

  async function synthesizeStandups() {
    if (!teamStandups.length) return;
    setSynthesizing(true);
    setSynthesis(null);
    try {
      const summaries = teamStandups.slice(0, 8).map((s) =>
        `${s.engineer}: Yesterday — ${s.yesterday}. Today — ${s.today}. Blockers — ${s.blockers || "none"}.`
      ).join("\n");
      const resp = await novaQuery(
        `Synthesize these standups into a 2-sentence team summary for the engineering manager. Highlight any shared blockers or themes. Standups:\n${summaries}`,
        "all"
      );
      setSynthesis(resp.answer ?? "Could not synthesize standups.");
    } catch {
      toast.error("EOS could not synthesize standups");
    } finally {
      setSynthesizing(false);
    }
  }

  // Collection status: who has vs hasn't submitted
  const expectedMembers = useMemo(() => {
    const seen = new Set(teamStandups.map((s) => s.engineer));
    const allEngineers = filtersData?.users ?? [];
    return allEngineers.map((e: string) => ({ name: e, submitted: seen.has(e) }));
  }, [teamStandups, filtersData]);

  const blockers = teamStandups.filter((s) => s.blockers && s.blockers.trim().length > 0);

  return (
    <div className={styles.page}>
      {/* Header */}
      <div className={styles.header}>
        <div>
          <h1 className={styles.title}>Daily Standup</h1>
          <p className={styles.subtitle}>AI-generated standups for the team</p>
        </div>
        <button
          className={`btn btn-primary ${styles.genBtn}`}
          onClick={() => generateMut.mutate()}
          disabled={generateMut.isPending}
        >
          {generateMut.isPending ? (
            <><span className={styles.spinner} />Generating…</>
          ) : (
            <><span className={styles.novaIcon}>✦</span> Generate with EOS</>
          )}
        </button>
      </div>

      {/* My Standup */}
      {!isManager && (
        <div className={styles.myStandup}>
          <div className={styles.myTitle}>My Standup — Today</div>
          {loadingMine ? (
            <p className={styles.empty}>Loading…</p>
          ) : myStandup ? (
            editing?.id === myStandup.id ? (
              <div className={styles.editForm}>
                <div className={styles.editField}>
                  <label>Yesterday</label>
                  <textarea className="input" rows={3} value={editForm.yesterday}
                    onChange={(e) => setEditForm(p => ({ ...p, yesterday: e.target.value }))} />
                </div>
                <div className={styles.editField}>
                  <label>Today</label>
                  <textarea className="input" rows={3} value={editForm.today}
                    onChange={(e) => setEditForm(p => ({ ...p, today: e.target.value }))} />
                </div>
                <div className={styles.editField}>
                  <label>Blockers</label>
                  <textarea className="input" rows={2} value={editForm.blockers}
                    onChange={(e) => setEditForm(p => ({ ...p, blockers: e.target.value }))} />
                </div>
                <div className={styles.editActions}>
                  <button className="btn btn-primary btn-sm" onClick={saveEdit}>Save</button>
                  <button className="btn btn-ghost btn-sm" onClick={() => setEditing(null)}>Cancel</button>
                </div>
              </div>
            ) : (
              <StandupCard standup={myStandup} onEdit={() => startEdit(myStandup)} showEdit />
            )
          ) : (
            <div className={styles.noStandup}>
              <p>No standup generated yet. Click "Generate with EOS" to create one.</p>
            </div>
          )}
        </div>
      )}

      {/* Manager View */}
      {isManager && (
        <>
          {/* ── EOS Autonomous Standup Panel ── */}
          <div className={styles.eosPanel}>
            <div className={styles.eosPanelHeader}>
              <RiSparklingLine size={13} color="var(--accent)" />
              <span className={styles.eosPanelTitle}>EOS Standup Intelligence</span>
              <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
              <button
                className={styles.synthesizeBtn}
                onClick={synthesizeStandups}
                disabled={synthesizing || teamStandups.length === 0}
              >
                {synthesizing ? <><span className={styles.synSpinner} /> Synthesizing…</> : <><RiSparklingLine size={11} /> Synthesize Team</>}
              </button>
            </div>

            <div className={styles.eosPanelBody}>
              {/* Collection Status */}
              {expectedMembers.length > 0 && (
                <div className={styles.collectionStatus}>
                  <div className={styles.collectionTitle}>Collection Status</div>
                  <div className={styles.collectionGrid}>
                    {expectedMembers.map((m) => (
                      <div key={m.name} className={`${styles.collectionMember} ${m.submitted ? styles.collectionSubmitted : styles.collectionMissing}`}>
                        {m.submitted ? <RiCheckboxCircleLine size={11} /> : <RiTimeLine size={11} />}
                        <span>{m.name}</span>
                      </div>
                    ))}
                  </div>
                  <div className={styles.collectionStat}>
                    {expectedMembers.filter((m) => m.submitted).length}/{expectedMembers.length} submitted
                    {expectedMembers.filter((m) => !m.submitted).length > 0 && (
                      <span className={styles.collectionPending}> · {expectedMembers.filter((m) => !m.submitted).length} pending</span>
                    )}
                  </div>
                </div>
              )}

              {/* Blockers aggregate */}
              {blockers.length > 0 && (
                <div className={styles.blockersAggregate}>
                  <div className={styles.blockersTitle}><RiAlertLine size={11} /> Active Blockers</div>
                  {blockers.map((s) => (
                    <div key={s.id} className={styles.blockerRow}>
                      <span className={styles.blockerName}>{s.engineer}</span>
                      <span className={styles.blockerText}>{s.blockers}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Synthesis output */}
              {synthesis && (
                <div className={styles.synthesisOutput}>
                  <div className={styles.synthesisLabel}><RiSparklingLine size={10} /> EOS Team Summary</div>
                  <p className={styles.synthesisText}>{synthesis}</p>
                </div>
              )}
            </div>
          </div>

          <div className={styles.filters}>
            <input
              type="date"
              className="input input-sm"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
            />
            <select
              className="input input-sm"
              value={selectedPod}
              onChange={(e) => setSelectedPod(e.target.value)}
            >
              <option value="">All PODs</option>
              {(filtersData?.pods ?? []).map((p) => <option key={p}>{p}</option>)}
            </select>
          </div>

          {isLoading ? (
            <p className={styles.empty}>Loading…</p>
          ) : teamStandups.length === 0 ? (
            <div className={styles.emptyState}>
              <span className={styles.emptyIcon}>☀️</span>
              <p>No standups for {selectedDate}{selectedPod ? ` in ${selectedPod}` : ""}.</p>
            </div>
          ) : (
            Object.entries(grouped).map(([pod, standups]) => (
              <div key={pod} className={styles.podGroup}>
                <div className={styles.podHeader}>{pod} <span className={styles.podCount}>{standups.length}</span></div>
                <div className={styles.cardGrid}>
                  {standups.map((s) => (
                    <StandupCard
                      key={s.id}
                      standup={s}
                      onEdit={() => startEdit(s)}
                      showEdit={s.engineer === user?.name}
                    />
                  ))}
                </div>
              </div>
            ))
          )}
        </>
      )}

      {/* Edit Modal */}
      {editing && editing.id !== myStandup?.id && (
        <div className={styles.overlay} onClick={(e) => e.target === e.currentTarget && setEditing(null)}>
          <div className={styles.editModal}>
            <h3 className={styles.modalTitle}>Edit Standup — {editing.engineer}</h3>
            <div className={styles.editForm}>
              <div className={styles.editField}>
                <label>Yesterday</label>
                <textarea className="input" rows={4} value={editForm.yesterday}
                  onChange={(e) => setEditForm(p => ({ ...p, yesterday: e.target.value }))} />
              </div>
              <div className={styles.editField}>
                <label>Today</label>
                <textarea className="input" rows={4} value={editForm.today}
                  onChange={(e) => setEditForm(p => ({ ...p, today: e.target.value }))} />
              </div>
              <div className={styles.editField}>
                <label>Blockers</label>
                <textarea className="input" rows={2} value={editForm.blockers}
                  onChange={(e) => setEditForm(p => ({ ...p, blockers: e.target.value }))} />
              </div>
              <div className={styles.editActions}>
                <button className="btn btn-ghost" onClick={() => setEditing(null)}>Cancel</button>
                <button className="btn btn-primary" onClick={saveEdit}>Save</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StandupCard({ standup, onEdit, showEdit }: { standup: Standup; onEdit: () => void; showEdit?: boolean }) {
  const initials = (standup.engineer || "").split(" ").map((n) => n[0]).join("").slice(0, 2);
  return (
    <div className={styles.standupCard}>
      <div className={styles.cardHeader}>
        <div className={styles.avatar}>{initials || "—"}</div>
        <div className={styles.cardMeta}>
          <span className={styles.engineer}>{standup.engineer || "—"}</span>
          {standup.pod ? <span className={styles.pod}>{standup.pod}</span> : null}
        </div>
        <div className={styles.cardActions}>
          {standup.shared && <span className={styles.sharedBadge}>Shared</span>}
          {showEdit && <button className={styles.editBtn} onClick={onEdit}>Edit</button>}
        </div>
      </div>
      <div className={styles.standupSection}>
        <div className={styles.sectionLabel}>Yesterday</div>
        <p className={styles.sectionText}>{standup.yesterday || "—"}</p>
      </div>
      <div className={styles.standupSection}>
        <div className={styles.sectionLabel}>Today</div>
        <p className={styles.sectionText}>{standup.today || "—"}</p>
      </div>
      {standup.blockers && (
        <div className={`${styles.standupSection} ${styles.blockerSection}`}>
          <div className={styles.sectionLabel}>⚠ Blockers</div>
          <p className={styles.sectionText}>{standup.blockers}</p>
        </div>
      )}
    </div>
  );
}
