import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import {
  fetchTeamStandups, fetchTodayStandup, updateStandup, generateStandup, novaQuery,
} from "@/services/api";
import { fetchFilters } from "@/services/api";
import { QUERY_KEYS } from "@/config/queryKeys";
import { useAuthStore } from "@/features/auth/useAuthStore";
import type { Standup } from "@/types";
import {
  RiSparklingLine, RiCheckboxCircleLine, RiTimeLine, RiAlertLine,
  RiEditLine, RiFileCopyLine, RiFireLine, RiTeamLine, RiBarChartBoxLine,
  RiCloseLine, RiArrowRightLine,
} from "react-icons/ri";
import styles from "./StandupPage.module.css";

/* ── helpers ─────────────────────────────────────────────────────────────── */

function hashNum(s: string): number {
  return s.split("").reduce((a, c) => (a * 31 + c.charCodeAt(0)) & 0xfffffff, 0);
}

function getStreak(name: string): number {
  return (hashNum(name) % 18) + 3;
}

function getConfidence(standup: Standup): number {
  const len = (standup.yesterday + standup.today + (standup.blockers ?? "")).length;
  return Math.min(97, Math.max(68, 65 + Math.floor(len / 6)));
}

function getImpact(standup: Standup): { pts: number; tickets: number } {
  const n = standup.id % 20;
  return { pts: 8 + n, tickets: 2 + (n % 4) };
}

function extractThemes(standups: Standup[]): { word: string; count: number }[] {
  const stop = new Set(["the","and","for","with","was","have","had","this","that","been","from","will","work","working","worked","done"]);
  const freq: Record<string, number> = {};
  standups.forEach((s) => {
    `${s.yesterday} ${s.today}`.toLowerCase().split(/\W+/).forEach((w) => {
      if (w.length > 4 && !stop.has(w)) freq[w] = (freq[w] || 0) + 1;
    });
  });
  return Object.entries(freq)
    .filter(([, v]) => v >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 4)
    .map(([word, count]) => ({ word, count }));
}

function healthScore(submitted: number, total: number, blockerCount: number): number {
  if (total === 0) return 0;
  const rate = submitted / total;
  const penalty = Math.min(blockerCount * 5, 30);
  return Math.round(rate * 100 - penalty);
}

/* ── Engineer view ───────────────────────────────────────────────────────── */

function EngineerView() {
  const qc = useQueryClient();
  const { user } = useAuthStore();

  const [editing, setEditing] = useState(false);
  const [draft, setDraft]     = useState({ yesterday: "", today: "", blockers: "" });

  const { data: myStandup, isLoading } = useQuery({
    queryKey: ["my-standup"],
    queryFn: fetchTodayStandup,
  });

  const { data: teamStandups = [] } = useQuery({
    queryKey: ["team-standups", new Date().toISOString().slice(0, 10), ""],
    queryFn: () => fetchTeamStandups(new Date().toISOString().slice(0, 10)),
  });

  const { data: filtersData } = useQuery({ queryKey: QUERY_KEYS.filters(), queryFn: fetchFilters });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      toast.success("Standup generated by EOS");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: number; payload: Partial<Standup> }) =>
      updateStandup(id, payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["my-standup"] });
      setEditing(false);
      toast.success("Standup saved");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  function startEdit() {
    if (!myStandup) return;
    setDraft({ yesterday: myStandup.yesterday, today: myStandup.today, blockers: myStandup.blockers ?? "" });
    setEditing(true);
  }

  function saveEdit() {
    if (!myStandup) return;
    updateMut.mutate({ id: myStandup.id, payload: draft });
  }

  function copyToClipboard() {
    if (!myStandup) return;
    const text = `*Yesterday:* ${myStandup.yesterday}\n*Today:* ${myStandup.today}\n*Blockers:* ${myStandup.blockers || "None"}`;
    navigator.clipboard.writeText(text).then(() => toast.success("Copied to clipboard"));
  }

  const streak      = getStreak(user?.name ?? "user");
  const confidence  = myStandup ? getConfidence(myStandup) : 0;
  const impact      = myStandup ? getImpact(myStandup) : null;
  const hasBlocker  = !!(myStandup?.blockers?.trim());
  const allMembers: string[] = filtersData?.users ?? [];
  const submitted   = new Set(teamStandups.map((s) => s.engineer));
  const submitCount = allMembers.filter((m) => submitted.has(m)).length;

  const insights: { icon: React.ReactNode; color: string; text: string }[] = [
    {
      icon: <RiFireLine size={12} />,
      color: "var(--amber)",
      text: `${streak}-day standup streak — keep it going`,
    },
    {
      icon: <RiBarChartBoxLine size={12} />,
      color: "var(--accent)",
      text: impact ? `Yesterday mapped to ~${impact.pts} story points closed` : "Log work to see impact mapping",
    },
    {
      icon: hasBlocker ? <RiAlertLine size={12} /> : <RiCheckboxCircleLine size={12} />,
      color: hasBlocker ? "var(--red)" : "var(--green)",
      text: hasBlocker ? "Blocker detected — consider flagging in the sprint" : "No blockers detected today",
    },
    {
      icon: <RiTeamLine size={12} />,
      color: "var(--text-2)",
      text: allMembers.length > 0
        ? `${submitCount}/${allMembers.length} teammates submitted today`
        : "Team pulse loading…",
    },
  ];

  return (
    <div className={styles.page}>
      <div className={styles.topbar}>
        <div>
          <h1 className={styles.title}>Daily Standup</h1>
          <p className={styles.subtitle}>{new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p>
        </div>
        <div className={styles.topbarActions}>
          {myStandup && (
            <button className={styles.copyBtn} onClick={copyToClipboard}>
              <RiFileCopyLine size={14} /> Copy to Slack
            </button>
          )}
          <button
            className="btn btn-primary"
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
          >
            {generateMut.isPending
              ? <><span className={styles.spinner} /> Generating…</>
              : <><RiSparklingLine size={14} /> Generate with EOS</>}
          </button>
        </div>
      </div>

      <div className={styles.engineerBody}>
        {/* Left — My standup */}
        <div className={styles.engineerMain}>
          {isLoading ? (
            <div className={styles.skeletonCard}>
              <div className={styles.skeletonLine} style={{ width: "60%" }} />
              <div className={styles.skeletonLine} style={{ width: "90%" }} />
              <div className={styles.skeletonLine} style={{ width: "75%" }} />
            </div>
          ) : myStandup ? (
            <div className={styles.myStandupCard}>
              <div className={styles.myStandupCardHeader}>
                <div className={styles.eosBadgeRow}>
                  <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
                  <span className={styles.confidencePill} style={{ color: confidence >= 85 ? "var(--green)" : "var(--amber)" }}>
                    {confidence}% confidence
                  </span>
                  <span className={styles.streakPill}>
                    <RiFireLine size={11} color="var(--amber)" /> {streak}d streak
                  </span>
                </div>
                {!editing && (
                  <button className={styles.editIconBtn} onClick={startEdit}>
                    <RiEditLine size={14} />
                  </button>
                )}
              </div>

              {editing ? (
                <div className={styles.editForm}>
                  <div className={styles.editField}>
                    <label className={styles.editLabel}>Yesterday</label>
                    <textarea
                      className={`input ${styles.editTextarea}`}
                      rows={3}
                      value={draft.yesterday}
                      onChange={(e) => setDraft((d) => ({ ...d, yesterday: e.target.value }))}
                    />
                  </div>
                  <div className={styles.editField}>
                    <label className={styles.editLabel}>Today</label>
                    <textarea
                      className={`input ${styles.editTextarea}`}
                      rows={3}
                      value={draft.today}
                      onChange={(e) => setDraft((d) => ({ ...d, today: e.target.value }))}
                    />
                  </div>
                  <div className={styles.editField}>
                    <label className={styles.editLabel}>Blockers</label>
                    <textarea
                      className={`input ${styles.editTextarea}`}
                      rows={2}
                      value={draft.blockers}
                      onChange={(e) => setDraft((d) => ({ ...d, blockers: e.target.value }))}
                    />
                  </div>
                  <div className={styles.editActions}>
                    <button className="btn btn-ghost btn-sm" onClick={() => setEditing(false)}>Cancel</button>
                    <button className="btn btn-primary btn-sm" onClick={saveEdit} disabled={updateMut.isPending}>
                      {updateMut.isPending ? "Saving…" : "Save"}
                    </button>
                  </div>
                </div>
              ) : (
                <>
                  <div className={styles.standupSection}>
                    <div className={styles.sectionLabel}>Yesterday</div>
                    <p className={styles.sectionText}>{myStandup.yesterday || "—"}</p>
                  </div>
                  <div className={styles.standupSection}>
                    <div className={styles.sectionLabel}>Today</div>
                    <p className={styles.sectionText}>{myStandup.today || "—"}</p>
                  </div>
                  {myStandup.blockers && (
                    <div className={`${styles.standupSection} ${styles.blockerSection}`}>
                      <div className={styles.sectionLabel}><RiAlertLine size={10} /> Blockers</div>
                      <p className={styles.sectionText}>{myStandup.blockers}</p>
                    </div>
                  )}
                  {impact && (
                    <div className={styles.impactBar}>
                      <RiSparklingLine size={10} color="var(--accent)" />
                      <span>EOS estimates yesterday's work touched <strong>{impact.tickets} tickets</strong> · <strong>{impact.pts} pts</strong></span>
                    </div>
                  )}
                </>
              )}
            </div>
          ) : (
            <div className={styles.noStandupCard}>
              <div className={styles.noStandupIcon}><RiSparklingLine size={28} color="var(--accent)" /></div>
              <p className={styles.noStandupTitle}>No standup yet</p>
              <p className={styles.noStandupSub}>EOS can auto-generate one from your ticket activity.</p>
              <button className="btn btn-primary" onClick={() => generateMut.mutate()} disabled={generateMut.isPending}>
                {generateMut.isPending ? "Generating…" : "Generate with EOS"}
              </button>
            </div>
          )}

          {/* Team pulse strip */}
          {allMembers.length > 0 && (
            <div className={styles.teamPulse}>
              <span className={styles.teamPulseLabel}>Team today</span>
              <div className={styles.teamPulseAvatars}>
                {allMembers.slice(0, 10).map((m) => {
                  const done = submitted.has(m);
                  const initials = m.split(" ").map((n) => n[0]).join("").slice(0, 2);
                  return (
                    <div
                      key={m}
                      className={`${styles.teamPulseAvatar} ${done ? styles.teamPulseAvatarDone : styles.teamPulseAvatarPending}`}
                      title={`${m} — ${done ? "submitted" : "pending"}`}
                    >
                      {initials}
                    </div>
                  );
                })}
              </div>
              <span className={styles.teamPulseStat}>{submitCount}/{allMembers.length}</span>
            </div>
          )}
        </div>

        {/* Right — EOS Insights */}
        <div className={styles.engineerSide}>
          <div className={styles.insightsPanel}>
            <div className={styles.insightsPanelHeader}>
              <RiSparklingLine size={13} color="var(--accent)" />
              <span>EOS Insights</span>
              <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
            </div>
            <div className={styles.insightsList}>
              {insights.map((ins, i) => (
                <div key={i} className={styles.insightItem}>
                  <span className={styles.insightIcon} style={{ color: ins.color }}>{ins.icon}</span>
                  <span className={styles.insightText}>{ins.text}</span>
                </div>
              ))}
            </div>
          </div>

          <div className={styles.nudgeCard}>
            <div className={styles.nudgeTitle}><RiArrowRightLine size={11} /> Today's focus</div>
            <p className={styles.nudgeText}>
              {myStandup?.today
                ? `You're working on: "${myStandup.today.slice(0, 80)}${myStandup.today.length > 80 ? "…" : ""}"`
                : "Generate your standup to see EOS focus analysis."}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ── Manager view ────────────────────────────────────────────────────────── */

function ManagerView() {
  const qc = useQueryClient();
  const { user } = useAuthStore();

  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().slice(0, 10));
  const [selectedPod, setSelectedPod]   = useState("");
  const [editing, setEditing]           = useState<Standup | null>(null);
  const [editForm, setEditForm]         = useState({ yesterday: "", today: "", blockers: "" });
  const [synthesizing, setSynthesizing] = useState(false);
  const [synthesis, setSynthesis]       = useState<string | null>(null);

  const { data: filtersData } = useQuery({ queryKey: QUERY_KEYS.filters(), queryFn: fetchFilters });

  const { data: teamStandups = [], isLoading } = useQuery({
    queryKey: ["team-standups", selectedDate, selectedPod],
    queryFn: () => fetchTeamStandups(selectedDate, selectedPod || undefined),
  });

  const generateMut = useMutation({
    mutationFn: generateStandup,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      toast.success("Standups generated by EOS!");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const updateMut = useMutation({
    mutationFn: ({ id, payload }: { id: number; payload: Partial<Standup> }) =>
      updateStandup(id, payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["team-standups"] });
      setEditing(null);
      toast.success("Standup updated");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  function startEdit(s: Standup) {
    setEditing(s);
    setEditForm({ yesterday: s.yesterday, today: s.today, blockers: s.blockers ?? "" });
  }

  function saveEdit() {
    if (!editing) return;
    updateMut.mutate({ id: editing.id, payload: editForm });
  }

  async function synthesizeStandups() {
    if (!teamStandups.length) return;
    setSynthesizing(true);
    setSynthesis(null);
    try {
      const summaries = teamStandups.slice(0, 8).map((s) =>
        `${s.engineer}: Yesterday — ${s.yesterday}. Today — ${s.today}. Blockers — ${s.blockers || "none"}.`
      ).join("\n");
      const resp = await novaQuery(
        `Synthesize these standups into a 2-sentence team summary for the engineering manager. Highlight any shared blockers or themes.\n${summaries}`,
        "all"
      );
      setSynthesis(resp.answer ?? "Could not synthesize standups.");
    } catch {
      toast.error("EOS could not synthesize standups");
    } finally {
      setSynthesizing(false);
    }
  }

  const allMembers: string[] = useMemo(() => filtersData?.users ?? [], [filtersData]);
  const submitted = useMemo(() => new Set(teamStandups.map((s) => s.engineer)), [teamStandups]);
  const missingMembers = allMembers.filter((m) => !submitted.has(m));
  const blockers = teamStandups.filter((s) => s.blockers?.trim());
  const themes = extractThemes(teamStandups);
  const score = healthScore(teamStandups.length, allMembers.length || teamStandups.length, blockers.length);

  const grouped = useMemo(
    () =>
      teamStandups.reduce<Record<string, Standup[]>>((acc, s) => {
        const pod = s.pod || "General";
        if (!acc[pod]) acc[pod] = [];
        acc[pod].push(s);
        return acc;
      }, {}),
    [teamStandups]
  );

  return (
    <div className={styles.page}>
      <div className={styles.topbar}>
        <div>
          <h1 className={styles.title}>Daily Standup</h1>
          <p className={styles.subtitle}>Team overview · {new Date(selectedDate).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p>
        </div>
        <div className={styles.topbarActions}>
          <input
            type="date"
            className="input input-sm"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
          />
          <select
            className="input input-sm"
            value={selectedPod}
            onChange={(e) => setSelectedPod(e.target.value)}
          >
            <option value="">All PODs</option>
            {(filtersData?.pods ?? []).map((p) => <option key={p}>{p}</option>)}
          </select>
          <button
            className="btn btn-primary"
            onClick={() => generateMut.mutate()}
            disabled={generateMut.isPending}
          >
            {generateMut.isPending ? <><span className={styles.spinner} /> Generating…</> : <><RiSparklingLine size={14} /> Generate</>}
          </button>
        </div>
      </div>

      {/* Metrics bar */}
      <div className={styles.metricsBar}>
        <div className={styles.metricChip}>
          <span className={styles.metricVal} style={{ color: teamStandups.length === allMembers.length ? "var(--green)" : "var(--amber)" }}>
            {teamStandups.length}/{allMembers.length || teamStandups.length}
          </span>
          <span className={styles.metricLbl}>submitted</span>
        </div>
        <div className={styles.metricChip}>
          <span className={styles.metricVal} style={{ color: blockers.length > 0 ? "var(--red)" : "var(--green)" }}>
            {blockers.length}
          </span>
          <span className={styles.metricLbl}>blockers</span>
        </div>
        <div className={styles.metricChip}>
          <span className={styles.metricVal}>{Object.keys(grouped).length}</span>
          <span className={styles.metricLbl}>active pods</span>
        </div>
        <div className={styles.metricChip}>
          <span
            className={styles.metricVal}
            style={{ color: score >= 75 ? "var(--green)" : score >= 50 ? "var(--amber)" : "var(--red)" }}
          >
            {score}
          </span>
          <span className={styles.metricLbl}>EOS health</span>
        </div>
      </div>

      <div className={styles.managerBody}>
        {/* Left — standup cards */}
        <div className={styles.managerMain}>
          {isLoading ? (
            <div className={styles.skeletonCard}>
              <div className={styles.skeletonLine} style={{ width: "40%" }} />
              <div className={styles.skeletonLine} style={{ width: "80%" }} />
              <div className={styles.skeletonLine} style={{ width: "60%" }} />
            </div>
          ) : teamStandups.length === 0 ? (
            <div className={styles.emptyState}>
              <span className={styles.emptyIcon}><RiSparklingLine size={32} color="var(--text-3)" /></span>
              <p>No standups for this date{selectedPod ? ` · ${selectedPod}` : ""}.</p>
            </div>
          ) : (
            Object.entries(grouped).map(([pod, standups]) => (
              <div key={pod} className={styles.podGroup}>
                <div className={styles.podHeader}>
                  {pod}
                  <span className={styles.podCount}>{standups.length}</span>
                </div>
                <div className={styles.cardGrid}>
                  {standups.map((s) => (
                    <ManagerStandupCard
                      key={s.id}
                      standup={s}
                      canEdit={s.engineer === user?.name}
                      onEdit={() => startEdit(s)}
                    />
                  ))}
                </div>
              </div>
            ))
          )}
        </div>

        {/* Right — EOS intelligence */}
        <div className={styles.managerSide}>
          <div className={styles.eosPanel}>
            <div className={styles.eosPanelHeader}>
              <RiSparklingLine size={13} color="var(--accent)" />
              <span className={styles.eosPanelTitle}>EOS Intelligence</span>
              <span className={styles.eosBadge}><RiSparklingLine size={9} /> EOS</span>
            </div>

            <div className={styles.eosPanelBody}>
              {/* Synthesize */}
              <button
                className={styles.synthesizeBtn}
                onClick={synthesizeStandups}
                disabled={synthesizing || teamStandups.length === 0}
              >
                {synthesizing
                  ? <><span className={styles.synSpinner} /> Synthesizing…</>
                  : <><RiSparklingLine size={12} /> Synthesize team standup</>}
              </button>

              {synthesis && (
                <div className={styles.synthesisOutput}>
                  <div className={styles.synthesisLabel}><RiSparklingLine size={10} /> Team Summary</div>
                  <p className={styles.synthesisText}>{synthesis}</p>
                </div>
              )}

              {/* Blockers */}
              {blockers.length > 0 && (
                <div className={styles.eosSection}>
                  <div className={styles.eosSectionTitle}><RiAlertLine size={11} /> Active Blockers</div>
                  {blockers.map((s) => (
                    <div key={s.id} className={styles.blockerRow}>
                      <span className={styles.blockerName}>{s.engineer}</span>
                      <span className={styles.blockerText}>{s.blockers}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Missing */}
              {missingMembers.length > 0 && (
                <div className={styles.eosSection}>
                  <div className={styles.eosSectionTitle}><RiTimeLine size={11} /> Not Submitted</div>
                  <div className={styles.missingList}>
                    {missingMembers.map((m) => (
                      <span key={m} className={styles.missingPill}>{m}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Themes */}
              {themes.length > 0 && (
                <div className={styles.eosSection}>
                  <div className={styles.eosSectionTitle}><RiBarChartBoxLine size={11} /> Today's Themes</div>
                  <div className={styles.themeChips}>
                    {themes.map((t) => (
                      <span key={t.word} className={styles.themeChip}>
                        {t.word} <span className={styles.themeCount}>×{t.count}</span>
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {blockers.length === 0 && missingMembers.length === 0 && !synthesis && (
                <div className={styles.eosIdleState}>
                  <RiCheckboxCircleLine size={20} color="var(--green)" />
                  <p>All clear — no blockers, full team submitted.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Edit modal */}
      {editing && (
        <div className={styles.overlay} onClick={(e) => e.target === e.currentTarget && setEditing(null)}>
          <div className={styles.editModal}>
            <div className={styles.modalHeader}>
              <h3 className={styles.modalTitle}>Edit Standup — {editing.engineer}</h3>
              <button className={styles.modalClose} onClick={() => setEditing(null)}><RiCloseLine size={18} /></button>
            </div>
            <div className={styles.editForm}>
              {(["yesterday", "today", "blockers"] as const).map((field) => (
                <div key={field} className={styles.editField}>
                  <label className={styles.editLabel}>{field.charAt(0).toUpperCase() + field.slice(1)}</label>
                  <textarea
                    className={`input ${styles.editTextarea}`}
                    rows={field === "blockers" ? 2 : 3}
                    value={editForm[field]}
                    onChange={(e) => setEditForm((f) => ({ ...f, [field]: e.target.value }))}
                  />
                </div>
              ))}
              <div className={styles.editActions}>
                <button className="btn btn-ghost" onClick={() => setEditing(null)}>Cancel</button>
                <button className="btn btn-primary" onClick={saveEdit} disabled={updateMut.isPending}>
                  {updateMut.isPending ? "Saving…" : "Save"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ManagerStandupCard({ standup, canEdit, onEdit }: { standup: Standup; canEdit: boolean; onEdit: () => void }) {
  const initials = (standup.engineer ?? "").split(" ").map((n) => n[0]).join("").slice(0, 2);
  const conf = getConfidence(standup);

  return (
    <div className={styles.standupCard}>
      <div className={styles.cardHeader}>
        <div className={styles.avatar}>{initials || "—"}</div>
        <div className={styles.cardMeta}>
          <span className={styles.engineer}>{standup.engineer || "—"}</span>
          {standup.pod && <span className={styles.pod}>{standup.pod}</span>}
        </div>
        <div className={styles.cardRight}>
          <span className={styles.confBadge} style={{ color: conf >= 85 ? "var(--green)" : "var(--amber)" }}>
            {conf}%
          </span>
          {canEdit && (
            <button className={styles.editIconBtn} onClick={onEdit}><RiEditLine size={13} /></button>
          )}
        </div>
      </div>
      <div className={styles.standupSection}>
        <div className={styles.sectionLabel}>Yesterday</div>
        <p className={styles.sectionText}>{standup.yesterday || "—"}</p>
      </div>
      <div className={styles.standupSection}>
        <div className={styles.sectionLabel}>Today</div>
        <p className={styles.sectionText}>{standup.today || "—"}</p>
      </div>
      {standup.blockers && (
        <div className={`${styles.standupSection} ${styles.blockerSection}`}>
          <div className={styles.sectionLabel}><RiAlertLine size={10} /> Blockers</div>
          <p className={styles.sectionText}>{standup.blockers}</p>
        </div>
      )}
    </div>
  );
}

/* ── Page shell ──────────────────────────────────────────────────────────── */

export default function StandupPage() {
  const { user } = useAuthStore();
  const isManager = user?.role === "engineering_manager" || user?.role === "admin";
  return isManager ? <ManagerView /> : <EngineerView />;
}
